commit-msg:
  commands:
    cog:
      run: cog verify --file {0}

pre-commit:
  parallel: true
  commands:
    format:
      glob: "*.{js,ts,tsx,jsx,json}"
      run: bunx biome check --staged --write --no-errors-on-unmatched
      stage_fixed: true

pre-push:
  commands:
    cog:
      run: cog check
    lint:
      run: bun run lint
