telemetry = false

[install]
smol = true
exact = true

[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = ".coverage"
coverageThreshold = { lines = 0.9, functions = 0.9 }
passWithNoTests = true
preload = ["./tests/setup.ts"]
pathIgnorePatterns = ["vendors/**", "drizzle/**"]
coveragePathIgnorePatterns = [
    "**/tests/**/fixtures/**",
    "apps/server/src/index.ts",
    "../ts-libs/**",
    "packages/domain/src/schema/**",
    "**/*.tsx",
]
