/**
 * TaskService — core task verbs over PlanningWriteService and direct corpus reads.
 *
 * Design §10, delivery §1.1. Read verbs never lock. Write verbs delegate to
 * PlanningWriteService. WBS allocation is race-safe under the create-lock.
 */

import { dirname, isAbsolute, relative, resolve } from 'node:path';
import type { TaskFolderEntry, TaskFoldersConfig } from '@gobing-ai/spur-config/loader';
import {
    atomicWriteAsync,
    buildTaskSkeleton,
    DEFAULT_TASK_VARIANT,
    MarkdownDocument,
    renderTaskTemplate,
    type TaskBatchItem,
    type TaskSection,
    taskBatchSchema,
} from '@gobing-ai/spur-domain';
import type { FileSystem } from '@gobing-ai/ts-runtime';
import type { SectionMatrix } from './planning-check-base';
import type { EntityRef, PlanningWriteService, WriteResult } from './planning-write-service';
import {
    gitDiffU0,
    type RecordOptions,
    type RecordResult,
    readVerdict,
    renderReview,
    renderSolutionFromDiff,
    renderTesting,
} from './task-record';

/**
 * Replace or add a frontmatter field in rendered markdown.
 * The rendered template carries placeholder defaults (e.g. `feature_id: null`,
 * `status: backlog`); this patches them to the create-time resolved values
 * before the file is written.
 *
 * YAML-aware: key must appear at line-start (no leading whitespace) so it
 * doesn't match inside a section body. A `null` default is replaced; a
 * non-existent key is appended before the closing `---` fence.
 */
function patchFrontmatterField(rendered: string, key: string, value: string): string {
    // Replace an existing key at line start (YAML frontmatter only).
    // The caller owns YAML formatting (formatYamlValue) — do NOT re-format here.
    const existingRe = new RegExp(`^(?=\\s*${escapeRegex(key)}:)`, 'm');
    if (existingRe.test(rendered)) {
        return rendered.replace(new RegExp(`^${escapeRegex(key)}:.*$`, 'm'), `${key}: ${value}`);
    }
    // Key not present — append before the closing `---` fence
    return rendered.replace(/^---\n/m, `---\n${key}: ${value}\n`);
}

function escapeRegex(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Wrap a value in double quotes when YAML would misinterpret it.
 * Covers: special characters, numeric-looking strings (e.g. WBS `0042`
 * would be parsed as octal), and the bare `null`/`true`/`false` literals.
 */
function formatYamlValue(value: string): string {
    if (/[:{}[\],&*?|>!%@`#"'\\\n\r]/.test(value)) return `"${value}"`;
    if (/^(null|true|false|yes|no|on|off)$/i.test(value)) return `"${value}"`;
    if (/^\d/.test(value) && !/^\d{4}-\d{2}-\d{2}/.test(value)) return `"${value}"`;
    return value;
}

// ─── Sub-task roster (0123) ───────────────────────────────────────────────

/** Auto-gen markers for the parent `## Plan` sub-task roster block. */
const ROSTER_START = '<!-- AUTO-GENERATED by spur task refresh-roster -->';
const ROSTER_END = '<!-- END AUTO-GENERATED -->';
/** Matches a full prior roster region (markers inclusive) for idempotent rewrite. */
const ROSTER_REGION_RE = /<!--[ \t]*AUTO-GENERATED[^>]*-->[\s\S]*?<!--[ \t]*END[ \t]*AUTO-GENERATED[^>]*-->/g;

/** Render the sub-task roster table — one row per child (WBS · title · status). */
function renderRosterTable(rows: { wbs: string; name: string; status: string }[]): string {
    const header = '| WBS | Sub-task | Status |\n| --- | -------- | ------ |';
    const body = rows.map((r) => `| ${r.wbs} | ${r.name.replace(/\|/g, '\\|')} | ${r.status} |`).join('\n');
    return `${header}\n${body}`;
}

// ─── Types ──────────────────────────────────────────────────────────────

/**
 * Per-folder configuration for WBS allocation. The canonical shape lives in
 * `@gobing-ai/spur-config` ({@link TaskFolderEntry}); re-exported under the
 * historical `FolderConfig` name so app consumers' imports stay stable (ADR-027).
 */
export type FolderConfig = TaskFolderEntry;

/**
 * Task-folder configuration sourced from the `tasks:` block in `.spur/config.yaml`.
 * Re-exported from the single config owner so the type identity is shared across the
 * loader↔service seam — no parallel definition (ADR-027).
 */
export type { TaskFoldersConfig };

/** Dependencies injected into TaskService. */
export interface TaskServiceContext {
    fs: FileSystem;
    writeService: PlanningWriteService;
    /** Tasks folder path (active_folder from config; see DEFAULT_TASKS_DIR). */
    tasksDir: string;
    /** Project name for atomic writes. */
    projectName?: string;
    /** Actor identifier for history lines (default: 'system'). */
    actor?: string;
    /**
     * Section-Status-Matrix. Drives which sections a newly created task carries
     * for its creation status (§3.2). When absent, a built-in default is used so
     * creation never hard-depends on a loadable matrix.
     */
    sectionMatrix?: SectionMatrix;
    /**
     * Resolve raw template content for a variant. Returns the template
     * markdown as-is (with `{{ PLACEHOLDERS }}` intact) so the create path
     * can render it with real values via `renderTaskTemplate`. When present,
     * `create()` uses template-as-skeleton rendering; when absent, creation
     * falls back to the legacy `buildTaskSkeleton` path.
     */
    resolveTemplate?: (variant: string) => string | undefined;
    /**
     * Resolve per-variant section-body overrides from the variant's template
     * file. Used by the legacy `buildTaskSkeleton` path (fallback when
     * `resolveTemplate` is absent) and by `batchCreate`. The caller (CLI)
     * owns file reading; returning `{}` (or omitting this) means matrix +
     * guidance only.
     */
    resolveTemplateBodies?: (variant: string) => Partial<Record<TaskSection, string>>;
    /**
     * Multi-folder configuration for WBS allocation. When absent, only
     * `tasksDir` is scanned. Mirrors the old rd3:tasks `config.jsonc` folders
     * model (global WBS uniqueness across all folders).
     */
    foldersConfig?: TaskFoldersConfig;
}

/** Job payload enqueued for async task actions. */
export interface TaskActionJob {
    wbs: string;
    action: string;
    command: string;
    channel?: string;
    skipDeps?: boolean;
}

/** Result returned by fulfillAction when a job is enqueued. */
export interface TaskActionResult {
    runId: string;
    action: string;
    status: 'queued';
}

/** Supported task workflow action names. */
export type TaskActionName = 'refine' | 'plan' | 'run' | 'verify' | 'decompose' | 'evaluate';

/** Action-to-slash-command table used by the task board action queue. */
export const TASK_ACTION_COMMANDS: Record<TaskActionName, (wbs: string) => string> = {
    refine: (wbs) => `/sp:dev-refine ${wbs} --auto`,
    plan: (wbs) => `/sp:dev-plan ${wbs} --auto`,
    run: (wbs) => `/sp:dev-run ${wbs} --auto`,
    verify: (wbs) => `/sp:dev-verify ${wbs} --auto`,
    decompose: (wbs) => `/sp:dev-plan "Decompose task ${wbs} into implementation subtasks" --auto`,
    evaluate: (wbs) => `/sp:dev-review ${wbs} --auto`,
};

function isTaskActionName(action: string): action is TaskActionName {
    return Object.hasOwn(TASK_ACTION_COMMANDS, action);
}

/** Task summary returned by list/show. */
export interface TaskSummary {
    wbs: string;
    name: string;
    status: string;
    /** Absolute file path. */
    filePath: string;
    frontmatter: Record<string, unknown>;
}

/** Show result: task summary + full markdown content. */
export interface TaskShowResult extends TaskSummary {
    /** The full markdown content. */
    content: string;
}

/**
 * Per-parent summary produced by `TaskService.batchCreate` (task 0178, F1/F2).
 * Surfaced alongside the children the batch created so the CLI can report which
 * parents were rostered / transitioned and what (if anything) failed.
 */
export interface ParentWireResult {
    /** Parent WBS. */
    wbs: string;
    /** True if the sub-task roster block was written (false on no-op / error). */
    rostered: boolean;
    /** New status after a successful transition, or `null` if the parent was not `todo`. */
    transitionedTo: string | null;
    /** Per-step error messages, empty when both steps succeeded. */
    errors: string[];
}

/** Filter options for the list verb. */
export interface TaskListFilters {
    status?: string;
    parentWbs?: string;
    /** Filter to tasks linked to this feature (the `feature_id` traceability edge). */
    featureId?: string;
    folder?: string;
    /** Legacy alias: 'phase' maps to status filter for backward compat. */
    phase?: string;
}

/**
 * Built-in section sets per creation status, used only when no Section-Status-
 * Matrix is injected (mirrors the shipped `config/tasks/section-matrix.yaml`
 * standard variant — keep in sync). `History` is appended by the resolver.
 */
const DEFAULT_CREATION_SECTIONS: Record<string, string[]> = {
    backlog: ['Background'],
    todo: ['Background', 'Requirements', 'Acceptance Criteria', 'Q&A', 'Design', 'Plan'],
};

/**
 * Normalize a Requirements body to a bulleted markdown list. R-numbered items
 * written as one run-on paragraph (`R1. … R2. …`) become one `- Rn. …` line
 * each, so they render as a clear list in a markdown viewer (dogfood issue #2).
 * Already-bulleted or multi-line input is returned unchanged.
 */
function bulletizeRequirements(raw: string): string {
    const text = raw.trim();
    if (text === '') return text;
    // Already a bullet/numbered list or multi-line — leave as authored.
    if (/\n/.test(text) || /^\s*[-*]\s/.test(text)) return text;
    const parts = text
        .split(/(?=\bR\d+\.)/)
        .map((p) => p.trim())
        .filter((p) => p.length > 0);
    if (parts.length <= 1) return text;
    return parts.map((p) => `- ${p}`).join('\n');
}

/**
 * Strip a redundant leading section header from `--from-file` body content (R1, task 0115).
 *
 * Agents naturally write a full section (`## Acceptance Criteria\n\n- [ ] AC1 …`) to the
 * temp file, but `--section` already names the section and the CLI supplies the canonical
 * heading. A leading heading line whose text matches `sectionName` (any level `#`–`######`,
 * case-insensitive) is therefore a duplicate — strip it and the blank lines that follow so
 * the body handed to `replaceSection` starts at the first real content line (no triple-newline
 * gap, no visual duplicate header). A heading that does NOT match the section name is left
 * alone — `replaceSection`'s same-level strip (R2) handles any phantom risk.
 */
function stripLeadingSectionHeader(body: string, sectionName: string): string {
    const match = body.match(/^(\s*)#{1,6}\s+(.+?)\s*(?:\n|$)/);
    if (match === null) return body;
    const headingText = (match[2] ?? '').trim();
    if (headingText.toLowerCase() !== sectionName.trim().toLowerCase()) return body;
    // Remove the heading line plus any leading whitespace and the blank lines after it.
    return body.slice(match[0].length).replace(/^\n+/, '');
}

// ─── Section bareness — used by pipeline steps to decide when to write ──

/**
 * Returns `true` if a named section is absent, empty/whitespace-only, guidance-comment-only,
 * or a known pipeline placeholder (the old `printf 'Pipeline run …'` stub).
 *
 * Used by the implement step (write `Solution` only when bare, never clobber
 * a hand-authored change-map) and the record step (backfill `Solution` safety-net,
 * skip `Testing`/`Review` if verify already populated them).
 */
export function sectionIsBare(doc: MarkdownDocument, name: string): boolean {
    if (!doc.hasSection(name)) return true;
    const body = doc.getSection(name);
    if (body === null) return true;
    const trimmed = body.replace(/<!--[\s\S]*?-->/g, '').trim();
    if (trimmed === '') return true;
    // Old pipeline placeholder: "Pipeline run <wbs> — …"
    if (/^Pipeline run \d{4}\b/.test(trimmed)) return true;
    return false;
}

// ─── TaskService ────────────────────────────────────────────────────────

/** Core task verbs over PlanningWriteService and direct corpus reads. */
export class TaskService {
    private readonly ctx: TaskServiceContext;
    private readonly writeService: PlanningWriteService;

    constructor(ctx: TaskServiceContext) {
        this.ctx = ctx;
        this.writeService = ctx.writeService;
    }

    /**
     * Resolve which sections a newly created task carries for `status`, from the
     * injected Section-Status-Matrix (`required ∪ optional`, §3.2). Falls back to
     * a built-in default when no matrix is available so creation never depends on
     * a loadable config (e.g. a `--compile` single binary). `History` is always
     * appended (the machine-owned transition log).
     */
    private sectionsForStatus(variant: string, status: string): string[] {
        const matrix = this.ctx.sectionMatrix;
        const entry = matrix?.variants[variant]?.[status] ?? matrix?.variants.standard?.[status];
        if (entry !== undefined) {
            return [...(entry.required ?? []), ...(entry.optional ?? []), 'History'];
        }
        const fallback = DEFAULT_CREATION_SECTIONS[status] ?? ['Background'];
        return [...fallback, 'History'];
    }

    /**
     * Merge per-variant template body overrides (e.g. `review`'s P1–P4 table)
     * with task-specific bodies (Background, Requirements). Task-specific bodies
     * win — the template supplies boilerplate, the task supplies real content.
     */
    private bodiesFor(
        variant: string,
        taskBodies: Partial<Record<TaskSection, string>>,
    ): Partial<Record<TaskSection, string>> {
        const templateBodies = this.ctx.resolveTemplateBodies?.(variant) ?? {};
        return { ...templateBodies, ...taskBodies };
    }

    // ── create ──

    async create(params: {
        title: string;
        featureId?: string;
        parentWbs?: string;
        status?: string;
        template?: string;
        actor?: string;
    }): Promise<WriteResult> {
        const folder = this.ctx.tasksDir;

        // Feature-derived Background is independent of the allocated WBS, so it
        // can be computed before the lock to keep the critical section short.
        let background = '';
        if (params.featureId !== undefined) {
            background = await this.deriveBackground(params.featureId);
        }

        // A feature link defaults the variant to `feature-impl`; otherwise `standard`.
        // An explicit --template always wins.
        const variant = params.template ?? (params.featureId !== undefined ? 'feature-impl' : DEFAULT_TASK_VARIANT);

        // WBS allocation + write run inside the create-lock so concurrent
        // creates cannot allocate the same number and clobber each other.
        // A task created with a feature link signals intent-to-execute → 'todo'
        // (the HITL-review stage); a bare capture stays 'backlog' (§2.3 semantics:
        // backlog = still preparing, todo = ready to start). Explicit status wins.
        const status = params.status ?? (params.featureId !== undefined ? 'todo' : 'backlog');

        return this.writeService.createAllocated(folder, async () => {
            const wbs = await this.allocateWbs();
            const slug = this.slugify(params.title);
            const filePath = this.resolveTaskPath(wbs, slug);

            const now = new Date().toISOString();

            // ── template-as-skeleton path (preferred) ──
            const rawTemplate = this.ctx.resolveTemplate?.(variant);
            if (rawTemplate !== undefined) {
                let content = renderTaskTemplate(rawTemplate, {
                    NAME: params.title,
                    WBS: wbs,
                    BACKGROUND: background,
                    CREATED_AT: now,
                    ...(params.featureId !== undefined ? { FEATURE_ID: params.featureId } : {}),
                });
                // Post-render frontmatter patching: the template carries defaults
                // (status: backlog, feature_id: null, etc.) — override with the
                // values determined by the create path.
                content = patchFrontmatterField(content, 'status', status);
                content = patchFrontmatterField(content, 'template', variant);
                if (params.featureId !== undefined) {
                    content = patchFrontmatterField(content, 'feature_id', formatYamlValue(params.featureId));
                }
                if (params.parentWbs !== undefined) {
                    content = patchFrontmatterField(content, 'parent_wbs', formatYamlValue(params.parentWbs));
                }
                const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder };
                return { ref, content };
            }

            // ── legacy buildTaskSkeleton fallback ──
            const frontmatter = [
                'schema_version: 1',
                `name: "${params.title}"`,
                `status: ${status}`,
                `template: ${variant}`,
                `created_at: ${now}`,
                `updated_at: ${now}`,
                params.featureId !== undefined ? `feature_id: ${params.featureId}` : null,
                params.parentWbs !== undefined ? `parent_wbs: "${params.parentWbs}"` : null,
            ]
                .filter(Boolean)
                .join('\n');

            const content = buildTaskSkeleton({
                wbs,
                title: params.title,
                frontmatter,
                sections: this.sectionsForStatus(variant, status),
                bodies: this.bodiesFor(variant, background !== '' ? { Background: background } : {}),
            });

            const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder };
            return { ref, content };
        });
    }

    // ── show ──

    async show(wbs: string): Promise<TaskShowResult> {
        const filePath = await this.resolveTaskFile(wbs);
        const raw = await this.ctx.fs.readFile(filePath);
        const doc = MarkdownDocument.parse(raw, 'task');
        const fm = doc.frontmatterData ?? {};

        return {
            wbs,
            name: (fm.name as string) ?? '',
            status: (fm.status as string) ?? '',
            filePath,
            frontmatter: fm as Record<string, unknown>,
            content: doc.bodyWithoutFrontmatter,
        };
    }

    // ── update (status transition) ──

    async updateStatus(wbs: string, toStatus: string, actor?: string): Promise<WriteResult> {
        const filePath = await this.resolveTaskFile(wbs);
        const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder: this.ctx.tasksDir };
        return this.writeService.transition(ref, toStatus, actor ?? this.ctx.actor ?? 'system');
    }

    // ── updateField (scalar frontmatter write) ──

    /**
     * Set a scalar frontmatter field on an existing task (e.g. `feature_id`,
     * `priority`). Closes the gap where these could only be set at `create` time.
     * The field allow-list keeps the surface narrow — status goes through the
     * lifecycle-guarded `updateStatus`, not here. The L1 schema still validates
     * the value after the write (e.g. an unknown priority is rejected).
     */
    async updateField(wbs: string, key: string, value: string): Promise<WriteResult> {
        const allowed = new Set(['feature_id', 'parent_wbs', 'priority']);
        if (!allowed.has(key)) {
            throw new Error(`Field "${key}" is not settable via update; allowed: ${[...allowed].join(', ')}.`);
        }
        const filePath = await this.resolveTaskFile(wbs);
        const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder: this.ctx.tasksDir };
        return this.writeService.updateFrontmatter(ref, key, value);
    }

    // ── updateBody (body region write) ──

    /**
     * Replace the task's markdown body — everything between the frontmatter and
     * the first `###` section heading. Frontmatter and named sections are untouched.
     *
     * `_actor` is accepted for transport parity with the contract's optional `actor`
     * input but is not used: a body write has no status change, so it appends no
     * `## History` line (history is gated on transitions) and there is nothing to
     * attribute. Kept wired so a future audit-log of body edits needs no signature change.
     */
    async updateBody(wbs: string, body: string, _actor?: string): Promise<WriteResult> {
        const filePath = await this.resolveTaskFile(wbs);
        const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder: this.ctx.tasksDir };
        return this.writeService.updateBody(ref, body);
    }

    // ── fulfillAction ──

    /**
     * Enqueue a task action (run, verify, etc.) for async execution.
     *
     * The caller provides `enqueue` — a function that persists the job and
     * returns the `runId`. The handler provides this via the server jobQueue;
     * the service owns only the business validation (task exists, action is
     * supported).
     *
     * @throws if the task file does not exist.
     */
    async fulfillAction(
        wbs: string,
        action: string,
        enqueue: (job: TaskActionJob) => Promise<string>,
        options?: { channel?: string; skipDeps?: boolean },
    ): Promise<TaskActionResult> {
        // Validate the task file exists (throws if not found).
        await this.resolveTaskFile(wbs);
        if (!isTaskActionName(action)) {
            throw new Error(`Unsupported task action: ${action}`);
        }

        const runId = await enqueue({
            wbs,
            action,
            command: TASK_ACTION_COMMANDS[action](wbs),
            channel: options?.channel,
            skipDeps: options?.skipDeps,
        });
        return { runId, action, status: 'queued' };
    }

    // ── update (section from file) ──

    async updateSection(wbs: string, sectionName: string, sourceFile: string): Promise<WriteResult> {
        const filePath = await this.resolveTaskFile(wbs);
        const raw = await this.ctx.fs.readFile(sourceFile);
        const body = stripLeadingSectionHeader(raw, sectionName);
        const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder: this.ctx.tasksDir };
        return this.writeService.updateSection(ref, sectionName, body);
    }

    // ── record (pipeline result write-back) ──

    /**
     * Record pipeline results into the task file: Testing + Review from the
     * verify verdict, and optionally backfill Solution from `git diff`.
     *
     * Design: docs/tasks/0108 — the single verb that replaces the pipeline's
     * ~50 lines of embedded shell. Section bodies are generated by pure functions
     * (unit-testable), then written through `writeService.updateSection` (upsert,
     * no temp files). Optionally transitions status (never to `done` — that gate
     * stays in the workflow).
     */
    async record(wbs: string, opts: RecordOptions = {}): Promise<RecordResult> {
        const filePath = await this.resolveTaskFile(wbs);
        const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder: this.ctx.tasksDir };

        // Read the current document to check section bareness for Solution backfill.
        const raw = await this.ctx.fs.readFile(filePath);
        const doc = MarkdownDocument.parse(raw, 'task');

        // Resolve verdict path.
        const verdictPath = opts.verdictFile ?? `.spur/run/${wbs}-verdict.json`;
        const verdict = await readVerdict(this.ctx.fs, verdictPath, wbs);

        const result: RecordResult = {
            testingWritten: false,
            reviewWritten: false,
            solutionBackfilled: false,
        };

        // ── Testing section (R2) ──
        const testingBody = renderTesting(verdict);
        await this.writeService.updateSection(ref, 'Testing', testingBody);
        result.testingWritten = true;

        // ── Review section (R2) — preserve existing review content ──
        // The review agent writes a detailed SECU Review during the `review` step.
        // Only overwrite with the verdict-rendered summary when the section is bare
        // (absent/placeholder), matching the Solution safety-net pattern.
        if (sectionIsBare(doc, 'Review')) {
            const reviewBody = renderReview(verdict);
            await this.writeService.updateSection(ref, 'Review', reviewBody);
            result.reviewWritten = true;
        }

        // ── Solution safety-net (R3) ──
        if (opts.solutionFromDiff && sectionIsBare(doc, 'Solution')) {
            const diffText = gitDiffU0();
            const solutionBody = renderSolutionFromDiff(diffText);
            await this.writeService.updateSection(ref, 'Solution', solutionBody);
            result.solutionBackfilled = true;
        }

        // ── Optional transition (R4) ──
        if (opts.transition !== undefined) {
            const transitionResult = await this.writeService.transition(ref, opts.transition);
            result.transitionedTo = transitionResult.toStatus;
        }

        return result;
    }

    // ── batch-create ──

    /**
     * Atomically create a batch of tasks from a JSON file, then wire up their
     * parents (R11 / G11 — this doc previously duplicated {@link ParentWireResult}'s
     * comment instead of describing this method).
     *
     * Steps:
     * 1. Read `jsonPath` and parse it as JSON; parse/schema failures throw
     *    (`batch validation failed: ...` lists every `taskBatchSchema` issue).
     * 2. Create each item in array order via {@link createBatchItem} (which itself
     *    allocates a fresh WBS under the create-lock, race-safe).
     * 3. If any item fails mid-batch, best-effort delete every task file already
     *    created in this call (no partial batch is left on disk), then rethrow.
     * 4. Post-create wire-up (task 0178, F1/F2): for each distinct `parent_wbs`
     *    seen in the batch, refresh its sub-task roster and transition it
     *    `todo → wip` if applicable — see {@link wireUpParents}.
     *
     * @param jsonPath Path to a batch file matching `taskBatchSchema` (a bare
     *   array of `{name, background?, requirements?, feature_id?, parent_wbs?,
     *   priority?, tags?, template?}` items).
     * @returns `children` — one {@link WriteResult} per created task, in the same
     *   order as the input array. `parentsWired` — one {@link ParentWireResult}
     *   per distinct parent touched by the wire-up pass.
     */
    async batchCreate(jsonPath: string): Promise<{ children: WriteResult[]; parentsWired: ParentWireResult[] }> {
        const raw = await this.ctx.fs.readFile(jsonPath);
        let parsed: unknown;
        try {
            parsed = JSON.parse(raw);
        } catch {
            throw new Error('batch file is not valid JSON');
        }

        const result = taskBatchSchema.safeParse(parsed);
        if (!result.success) {
            const issues = result.error.issues.map((i) => `  [${i.path.join('.')}] ${i.message}`).join('\n');
            throw new Error(`batch validation failed:\n${issues}`);
        }

        const items: TaskBatchItem[] = result.data;
        const writeResults: WriteResult[] = [];
        const createdRefs: EntityRef[] = [];

        try {
            for (const item of items) {
                const wr = await this.createBatchItem(item);
                writeResults.push(wr);
                createdRefs.push(wr.ref);
            }
        } catch (err) {
            for (const ref of createdRefs) {
                try {
                    await this.ctx.fs.deleteFile(ref.filePath);
                } catch {
                    // best-effort cleanup
                }
            }
            throw err;
        }

        const parentsWired = await this.wireUpParents(this.collectDistinctParents(items));
        return { children: writeResults, parentsWired };
    }

    /**
     * Distinct non-empty `parent_wbs` values from a validated batch, in first-seen
     * order. Skips `null` / `undefined` / empty-string — a childless top-level
     * task is fine. Used by `batchCreate` to know which parents need their roster
     * refreshed and lifecycle transitioned (F1/F2).
     */
    private collectDistinctParents(items: TaskBatchItem[]): string[] {
        const seen = new Set<string>();
        const ordered: string[] = [];
        for (const item of items) {
            const wbs = item.parent_wbs;
            if (typeof wbs !== 'string' || wbs === '') continue;
            if (seen.has(wbs)) continue;
            seen.add(wbs);
            ordered.push(wbs);
        }
        return ordered;
    }

    /**
     * Post-create wire-up pass. For each distinct parent in the batch:
     *   - refresh the sub-task roster (`refreshRoster` — idempotent, marker-delimited)
     *   - transition `todo → wip` if the parent is currently `todo` (F2; skip silently
     *     for every other status so a parent already `wip` or later is not re-noised)
     *
     * Best-effort per parent: a failure on one parent records an entry in the
     * returned `parentsWired` and the loop continues. Rolling children back when
     * a parent's wire-up fails would discard atomic-create success on a heuristic
     * guess; the children are already on disk and a follow-up `spur task
     * refresh-roster` / manual transition is the right escape hatch.
     */
    private async wireUpParents(parentWbsList: string[]): Promise<ParentWireResult[]> {
        const out: ParentWireResult[] = [];
        for (const wbs of parentWbsList) {
            const entry: ParentWireResult = { wbs, rostered: false, transitionedTo: null, errors: [] };
            try {
                const roster = await this.refreshRoster(wbs);
                entry.rostered = roster.written;
            } catch (err) {
                entry.errors.push(`refreshRoster: ${err instanceof Error ? err.message : String(err)}`);
            }
            try {
                const current = await this.show(wbs);
                if (current.status === 'todo') {
                    const filePath = await this.resolveTaskFile(wbs);
                    const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder: this.ctx.tasksDir };
                    const wr = await this.writeService.transition(ref, 'wip', 'system');
                    entry.transitionedTo = wr.toStatus ?? 'wip';
                } else {
                    entry.transitionedTo = null;
                }
            } catch (err) {
                entry.errors.push(`transition: ${err instanceof Error ? err.message : String(err)}`);
            }
            out.push(entry);
        }
        return out;
    }

    private async createBatchItem(item: TaskBatchItem): Promise<WriteResult> {
        const folder = this.ctx.tasksDir;

        // Feature-derived Background is WBS-independent — compute before the lock.
        let background = item.background ?? '';
        if (!background && item.feature_id !== undefined && item.feature_id !== null) {
            background = await this.deriveBackground(item.feature_id);
        }

        // A batch item with a real spec (background or requirements) is ready to
        // execute → 'todo'; otherwise 'backlog' (§2.3 semantics).
        const hasSpec = background !== '' || (item.requirements ?? '').trim() !== '';
        const status = hasSpec ? 'todo' : 'backlog';

        // Explicit item template wins; a feature link defaults to `feature-impl`, else `standard`.
        const variant =
            item.template ??
            (item.feature_id !== undefined && item.feature_id !== null ? 'feature-impl' : DEFAULT_TASK_VARIANT);

        // Allocate + write inside the create-lock (race-safe WBS allocation).
        return this.writeService.createAllocated(folder, async () => {
            const wbs = await this.allocateWbs();
            const slug = this.slugify(item.name);
            const filePath = this.resolveTaskPath(wbs, slug);

            const now = new Date().toISOString();

            // ── template-as-skeleton path (preferred) ──
            const rawTemplate = this.ctx.resolveTemplate?.(variant);
            if (rawTemplate !== undefined) {
                let content = renderTaskTemplate(rawTemplate, {
                    NAME: item.name,
                    WBS: wbs,
                    BACKGROUND: background,
                    CREATED_AT: now,
                    ...(item.feature_id !== undefined && item.feature_id !== null
                        ? { FEATURE_ID: item.feature_id }
                        : {}),
                });
                content = patchFrontmatterField(content, 'status', status);
                content = patchFrontmatterField(content, 'template', variant);
                if (item.feature_id !== undefined && item.feature_id !== null) {
                    content = patchFrontmatterField(content, 'feature_id', formatYamlValue(item.feature_id));
                }
                if (item.parent_wbs !== undefined && item.parent_wbs !== null) {
                    content = patchFrontmatterField(content, 'parent_wbs', formatYamlValue(item.parent_wbs));
                }
                if (item.priority !== undefined && item.priority !== null) {
                    content = patchFrontmatterField(content, 'priority', item.priority);
                }
                if (item.tags !== undefined && item.tags.length > 0) {
                    content = patchFrontmatterField(
                        content,
                        'tags',
                        `[${item.tags.map((tag) => JSON.stringify(tag)).join(', ')}]`,
                    );
                }
                if ((item.requirements ?? '').trim() !== '') {
                    const doc = MarkdownDocument.parse(content, 'task');
                    doc.replaceSection('Requirements', bulletizeRequirements(item.requirements ?? ''));
                    content = doc.serialize();
                }
                const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder };
                return { ref, content };
            }

            // ── legacy buildTaskSkeleton fallback ──
            const fmLines = [
                'schema_version: 1',
                `name: "${item.name}"`,
                `status: ${status}`,
                `template: ${variant}`,
                `created_at: ${now}`,
                `updated_at: ${now}`,
                item.feature_id !== undefined ? `feature_id: ${item.feature_id}` : null,
                item.parent_wbs !== undefined ? `parent_wbs: "${item.parent_wbs}"` : null,
                item.priority !== undefined ? `priority: ${item.priority}` : null,
                item.tags !== undefined && item.tags.length > 0
                    ? `tags: [${item.tags.map((t) => `"${t}"`).join(', ')}]`
                    : null,
            ]
                .filter(Boolean)
                .join('\n');

            const taskBodies: Partial<Record<TaskSection, string>> = {};
            if (background !== '') taskBodies.Background = background;
            if ((item.requirements ?? '').trim() !== '') {
                taskBodies.Requirements = bulletizeRequirements(item.requirements ?? '');
            }

            const content = buildTaskSkeleton({
                wbs,
                title: item.name,
                frontmatter: fmLines,
                sections: this.sectionsForStatus(variant, status),
                bodies: this.bodiesFor(variant, taskBodies),
            });

            const ref: EntityRef = { kind: 'task', id: wbs, filePath, folder };
            return { ref, content };
        });
    }

    // ── refresh ──

    /**
     * Re-scan the task corpus and report counts. The generated `kanban.md` artifact
     * was retired (A17 cutover) once the web task-kanban board (task 0191) became the
     * daily driver — this verb no longer writes any file.
     */
    async refresh(): Promise<{ folders: number; tasks: number }> {
        const folders = this.ctx.foldersConfig
            ? [...new Set([this.ctx.tasksDir, ...Object.keys(this.ctx.foldersConfig.folders)])]
            : [this.ctx.tasksDir];

        let totalTasks = 0;
        for (const folder of folders) {
            const tasks = await this.list({ folder });
            totalTasks += tasks.length;
        }
        return { folders: folders.length, tasks: totalTasks };
    }

    // ── refresh-roster (0123) ──

    /**
     * Regenerate a decomposition parent's sub-task roster inside its `## Plan` —
     * the generator half of the 0121 roll-up gate (which only *warns* about a
     * missing/stale roster). One row per child task (WBS · title · status),
     * written between auto-gen markers so the block is idempotent.
     *
     * The block is delimited by `refresh-roster`-labeled markers and rewritten in
     * place each run (replacing any prior roster block, or appended when absent),
     * preserving the hand-written Plan content above it (R1/R2). Region handling is
     * done here rather than via `MarkdownDocument.replaceMarkerRegion` — that helper
     * normalizes the marker label to "spur feature refresh", which would mislabel a
     * task roster.
     *
     * A task with zero children is a clean no-op (writes nothing, R4). A task with
     * no `## Plan` section is an error — there is nowhere to host the roster.
     */
    async refreshRoster(wbs: string): Promise<{ wbs: string; childCount: number; written: boolean }> {
        const filePath = await this.resolveTaskFile(wbs);
        const kids = (await this.list())
            .filter((t) => ((t.frontmatter.parent_wbs as string | undefined) ?? undefined) === wbs)
            .sort((a, b) => a.wbs.localeCompare(b.wbs));

        if (kids.length === 0) return { wbs, childCount: 0, written: false };

        const raw = await this.ctx.fs.readFile(filePath);
        const doc = MarkdownDocument.parse(raw, 'task');
        if (!doc.hasSection('Plan')) {
            throw new Error(`Task ${wbs} has no ## Plan section to host the sub-task roster`);
        }

        const table = renderRosterTable(
            kids.map((t) => ({
                wbs: t.wbs,
                name: (t.frontmatter.name as string | undefined) ?? t.name,
                status: t.status,
            })),
        );
        const block = `${ROSTER_START}\n${table}\n${ROSTER_END}`;

        const planBody = doc.getSection('Plan') ?? '';
        const stripped = planBody.replace(ROSTER_REGION_RE, '').trimEnd();
        doc.replaceSection('Plan', stripped.length > 0 ? `${stripped}\n\n${block}` : block);

        await atomicWriteAsync(filePath, doc.serialize(), wbs, this.ctx.fs, this.ctx.projectName ?? 'spur');
        return { wbs, childCount: kids.length, written: true };
    }

    // ── list ──

    async list(filters?: TaskListFilters): Promise<TaskSummary[]> {
        const dir = this.resolveListDir(filters?.folder);

        const entries = await this.ctx.fs.readDir(dir);
        const tasks: TaskSummary[] = [];

        for (const name of entries) {
            const [, wbs] = /^(\d{4})_.+\.md$/.exec(name) ?? [];
            if (!wbs) continue;
            // Read each file from the listed folder — not tasksDir — so a non-default
            // `folder` lists and reads consistently from the same directory.
            const actualPath = `${dir}/${name}`;
            try {
                const raw = await this.ctx.fs.readFile(actualPath);
                const doc = MarkdownDocument.parse(raw, 'task');
                const fm = doc.frontmatterData ?? {};
                const status = (fm.status as string) ?? '';
                const parentWbs = (fm.parent_wbs as string | null) ?? undefined;
                const featureId = (fm.feature_id as string | null) ?? undefined;

                if (filters?.status !== undefined && filters.status !== status) continue;
                if (filters?.parentWbs !== undefined && filters.parentWbs !== parentWbs) continue;
                if (filters?.featureId !== undefined && filters.featureId !== featureId) continue;
                if (filters?.phase !== undefined && filters.phase !== status) continue;

                tasks.push({
                    wbs,
                    name: (fm.name as string) ?? name,
                    status,
                    filePath: actualPath,
                    frontmatter: fm as Record<string, unknown>,
                });
            } catch {
                // Skip unparseable files
            }
        }
        return tasks;
    }

    // ── resolve ──

    /**
     * Resolve a file path to its owning task.
     *
     * Strategy 1 (always): exact match — the path IS a real corpus task file.
     * Strategy 2 (lenient, default): the basename alone encodes a known WBS, so a
     *   path anywhere (`/some/copy/0042_x.md`) resolves to corpus task 0042.
     *
     * `strict: true` disables Strategy 2. Use it when the question is "is this exact
     * path a protected corpus file?" (the write-guard) — a scratch file that merely
     * shares a `NNNN_` prefix (e.g. `/tmp/0103_design.md`) must NOT be claimed.
     */
    async resolve(
        filePath: string,
        opts: { strict?: boolean } = {},
    ): Promise<{ wbs: string; filePath: string } | null> {
        // Strategy 1: exact match against EVERY registered folder (not just the active
        // one) — the corpus may span folders (e.g. docs/tasks + docs/tasks2). Compare
        // normalized absolute paths so a relative or absolute input both match.
        const target = resolve(filePath);
        for (const dir of this.allFolderDirs()) {
            const hit = await this.exactMatchInDir(dir, target);
            if (hit !== null) return hit;
        }

        if (opts.strict === true) return null;

        // Strategy 2: parse a WBS out of the basename and resolve it in the corpus.
        const basename = filePath.split('/').pop() ?? '';
        const capturedWbs = /^(\d{4})_.+\.md$/.exec(basename)?.[1];
        if (capturedWbs) {
            const taskPath = await this.findWbsAcrossFolders(capturedWbs);
            if (taskPath !== null) return { wbs: capturedWbs, filePath: taskPath };
        }

        return null;
    }

    /** Locate WBS `wbs`'s file path across all registered folders (lenient Strategy 2). */
    private async findWbsAcrossFolders(wbs: string): Promise<string | null> {
        for (const dir of this.allFolderDirs()) {
            let entries: string[];
            try {
                entries = await this.ctx.fs.readDir(dir);
            } catch {
                continue;
            }
            for (const name of entries) {
                if (name.startsWith(`${wbs}_`) && name.endsWith('.md')) return `${dir}/${name}`;
            }
        }
        return null;
    }

    /**
     * All registered task-folder directories as absolute paths: the active `tasksDir`
     * plus every `foldersConfig.folders` key (resolved against the fs root). Deduped.
     * Mirrors `allocateWbs`'s folder enumeration so resolution and allocation agree.
     */
    private allFolderDirs(): string[] {
        const folderKeys = this.ctx.foldersConfig ? Object.keys(this.ctx.foldersConfig.folders) : [];
        const dirs = [this.ctx.tasksDir, ...folderKeys.map((key) => this.ctx.fs.resolve(key))];
        return [...new Set(dirs)];
    }

    /** Find the task whose real path equals `target` (already absolute) within one folder. */
    private async exactMatchInDir(dir: string, target: string): Promise<{ wbs: string; filePath: string } | null> {
        let entries: string[];
        try {
            entries = await this.ctx.fs.readDir(dir);
        } catch {
            return null; // folder may not exist yet
        }
        for (const name of entries) {
            const captured = /^(\d{4})_(.+)\.md$/.exec(name);
            if (captured === null) continue;
            const taskPath = `${dir}/${name}`;
            if (resolve(taskPath) === target) {
                return { wbs: captured[1] as string, filePath: taskPath };
            }
        }
        return null;
    }

    private async allocateWbs(): Promise<string> {
        // Scan ALL configured folders for global WBS uniqueness (rd3:tasks model).
        // Falls back to tasksDir-only when foldersConfig is absent.
        let max = 0;
        const dirs = this.ctx.foldersConfig
            ? [...new Set([this.ctx.tasksDir, ...Object.keys(this.ctx.foldersConfig.folders)])]
            : [this.ctx.tasksDir];

        for (const dir of dirs) {
            const baseCounter = this.ctx.foldersConfig?.folders[dir]?.base_counter ?? 0;
            if (baseCounter > max) max = baseCounter;
            try {
                const entries = await this.ctx.fs.readDir(dir);
                for (const name of entries) {
                    const [, digits] = /^(\d{4})_.*\.md$/.exec(name) ?? [];
                    if (digits) {
                        const n = parseInt(digits, 10);
                        if (n > max) max = n;
                    }
                }
            } catch {
                /* folder may not exist yet */
            }
        }
        return String(max + 1).padStart(4, '0');
    }

    /** Resolve a WBS to its absolute file path. Returns `null` when not found. */
    async getFilePath(wbs: string): Promise<string | null> {
        const fileName = await this.findTaskFileName(wbs);
        if (!fileName) return null;
        const slug = fileName.replace(/^\d{4}_/, '').replace(/\.md$/, '');
        return this.resolveTaskPath(wbs, slug);
    }

    private async resolveTaskFile(wbs: string): Promise<string> {
        const fileName = await this.findTaskFileName(wbs);
        if (!fileName) throw new Error(`Task ${wbs} not found in ${this.ctx.tasksDir}`);
        const slug = fileName.replace(/^\d{4}_/, '').replace(/\.md$/, '');
        return this.resolveTaskPath(wbs, slug);
    }

    private async findTaskFileName(wbs: string): Promise<string | null> {
        const entries = await this.ctx.fs.readDir(this.ctx.tasksDir);
        for (const name of entries) {
            if (name.startsWith(`${wbs}_`) && name.endsWith('.md')) return name;
        }
        return null;
    }

    private async deriveBackground(featureId: string): Promise<string> {
        const featuresDir = this.ctx.tasksDir.replace(/\/tasks$/, '/features');
        let entries: string[] = [];
        try {
            entries = await this.ctx.fs.readDir(featuresDir);
        } catch {
            return '';
        }
        for (const name of entries) {
            if (!name.match(/^[A-Z][1-9]*_.+\.md$/)) continue;
            try {
                const filePath = `${featuresDir}/${name}`;
                const raw = await this.ctx.fs.readFile(filePath);
                const doc = MarkdownDocument.parse(raw, 'feature');
                const fm = doc.frontmatterData ?? {};
                if (fm.id !== featureId) continue;
                if (fm.priority !== 'P0') continue;
                if (!['active', 'verifying'].includes(fm.status as string)) continue;
                const goal = doc.getSection('Goal') ?? '';
                return goal.trim();
            } catch {
                // Skip an unparseable feature file — Background derivation is best-effort.
            }
        }
        return '';
    }

    private resolveTaskPath(wbs: string, slug: string): string {
        return `${this.ctx.tasksDir}/${wbs}_${slug}.md`;
    }

    /**
     * Resolve the directory `list()` reads from. Defaults to `tasksDir`. A
     * caller-supplied `folder` (web/CLI param) is constrained to the planning
     * workspace — the parent of `tasksDir` (e.g. `docs/`, holding `tasks/` and
     * `features/`). `..` traversal or absolute paths that escape that root are
     * rejected, so an arbitrary `folder` over the wire cannot enumerate the host
     * filesystem outside the workspace.
     */
    private resolveListDir(folder?: string): string {
        if (folder === undefined) return this.ctx.tasksDir;
        const root = resolve(dirname(this.ctx.tasksDir));
        const candidate = resolve(root, folder);
        const rel = relative(root, candidate);
        if (rel.startsWith('..') || isAbsolute(rel)) {
            throw new Error(`Invalid folder: ${folder} escapes the planning workspace`);
        }
        return folder;
    }

    private slugify(title: string): string {
        return title
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '')
            .slice(0, 60);
    }
}
