/**
 * MarkdownDocument — the single markdown I/O layer for task and feature files.
 *
 * Design authority: rd3-migration-design.md §2.1/§2.2 heading conventions,
 * DD-08 (closed canonical section vocabulary), §2.2 auto-gen marker region.
 *
 * Core contract: **losslessness**. Untouched content round-trips byte-identically
 * through parse → serialize. Only explicitly modified sections or marker regions
 * change. This is what makes parse-validate-serialize safe to put under every write.
 *
 * Heading conventions (per domain):
 * - task: title is `## <WBS>. <name>`, sections are `### <Section>`
 * - feature: title is `# <ID>: <name>`, sections are `## <Section>`
 */
import { parse as parseYaml } from 'yaml';

/** Domain kind — determines heading level and canonical section vocabulary. */
export type MarkdownDomain = 'task' | 'feature';

/** Raw + parsed frontmatter. */
export interface ParsedFrontmatter {
    /** Raw YAML text between the `---` fences (excluding the fences themselves). */
    readonly raw: string;
    /** Parsed YAML as a plain object. Empty object on parse failure or non-object YAML. */
    readonly data: Record<string, unknown>;
}

/**
 * Canonical task body sections (DD-08). Templates select from this vocabulary;
 * no template or agent may invent synonym sections.
 */
export const TASK_CANONICAL_SECTIONS = [
    'Background',
    'Requirements',
    'Acceptance Criteria',
    'Q&A',
    'Design',
    'Plan',
    'Solution',
    'Root Cause',
    'Testing',
    'Review',
    'References',
    'History',
] as const;

/**
 * Canonical feature body sections. `## Tasks` is the auto-gen marker region
 * (the only machine-owned region in any SSOT file).
 */
export const FEATURE_CANONICAL_SECTIONS = [
    'Goal',
    'Scope',
    'Acceptance Criteria',
    'Tasks',
    'Notes',
    'History',
] as const;

/**
 * Sections allowed at every status without being declared in the matrix
 * (the closed-world relaxation, design §3.2). Domain owns this vocabulary;
 * the app layer imports it — no second inline definition.
 */
export const UNIVERSAL_SECTIONS = ['History', 'References', 'Notes'] as const;

/** Section heading level per domain: tasks use `###`, features use `##`. */
const HEADING_LEVELS: Record<MarkdownDomain, number> = { task: 3, feature: 2 };

/** Marker comment constants for auto-generated regions. */
const START_MARKER = '<!-- AUTO-GENERATED by spur feature refresh -->';
const END_MARKER = '<!-- END AUTO-GENERATED -->';

const MARKER_START_RE = /<!--[ \t]*AUTO-GENERATED.*?-->/;
const MARKER_END_RE = /<!--[ \t]*END[ \t]*AUTO-GENERATED.*?-->/;

interface Section {
    /** Canonical name extracted from the heading line (trimmed). */
    readonly name: string;
    /** Full heading line text (e.g., `### Background`). */
    readonly headingLine: string;
    /** Byte-exact original section text — heading + body — from the source. */
    readonly originalText: string;
    /** Replacement text (heading + modified body). `null` = use originalText. */
    modifiedText: string | null;
}

interface HeadingHit {
    index: number;
    headingLine: string;
    name: string;
}

/**
 * Find all section headings at the given level, skipping fenced code blocks.
 *
 * Scans line by line, tracking ``` toggle state. A heading is any line at
 * line-start that begins with `<hashes> ` (exact level — `####` won't match
 * a `###` scan). Returns character offsets into `body`.
 */
function findHeadings(body: string, hashes: string): HeadingHit[] {
    const hits: HeadingHit[] = [];
    const prefix = `${hashes} `;
    let inCodeBlock = false;
    let lineStart = 0;

    for (let i = 0; i <= body.length; i++) {
        const atEnd = i === body.length;
        if (!atEnd && body[i] !== '\n') continue;

        const line = body.slice(lineStart, i);

        if (line.startsWith('```')) {
            inCodeBlock = !inCodeBlock;
        } else if (!inCodeBlock && line.startsWith(prefix)) {
            const name = line.slice(prefix.length).trim();
            hits.push({ index: lineStart, headingLine: line, name });
        }

        lineStart = i + 1;
    }

    return hits;
}

/**
 * Unified markdown document with lossless frontmatter + section read/write.
 *
 * Usage:
 * ```ts
 * const doc = MarkdownDocument.parse(fileContent, 'task');
 * const bg = doc.getSection('Background');   // raw body text or null
 * doc.replaceSection('Solution', newBody);
 * doc.replaceMarkerRegion('Tasks', tableMarkdown); // feature only
 * const output = doc.serialize();             // byte-identical for untouched parts
 * ```
 */
export class MarkdownDocument {
    private readonly _domain: MarkdownDomain;
    private _frontmatterBlock: string;
    private _frontmatter: ParsedFrontmatter | null;
    private _preamble: string;
    private readonly _sections: Section[];
    /** Same-level heading lines stripped from section bodies during this doc's mutations (R2). */
    private readonly _strippedHeadings: string[] = [];
    /** Section names that appeared more than once in the source — dropped at parse time, keeping first. */
    private readonly _duplicateSectionNames: string[] = [];

    private constructor(
        domain: MarkdownDomain,
        frontmatterBlock: string,
        frontmatter: ParsedFrontmatter | null,
        preamble: string,
        sections: Section[],
    ) {
        this._domain = domain;
        this._frontmatterBlock = frontmatterBlock;
        this._frontmatter = frontmatter;
        this._preamble = preamble;
        this._sections = sections;
    }

    /**
     * Parse markdown content into a MarkdownDocument.
     *
     * Extracts optional YAML frontmatter (between `---` fences at the start of
     * the file) and splits the body into sections at domain-specific heading
     * boundaries. Headings inside fenced code blocks are ignored.
     */
    static parse(content: string, domain: MarkdownDomain): MarkdownDocument {
        const level = HEADING_LEVELS[domain];
        const hashes = '#'.repeat(level);

        // --- frontmatter ---
        let frontmatterBlock = '';
        let frontmatter: ParsedFrontmatter | null = null;
        let body = content;

        const fmRe = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;
        const fmMatch = fmRe.exec(content);
        if (fmMatch && fmMatch.index === 0) {
            const raw = fmMatch[1] ?? '';
            let data: Record<string, unknown> = {};
            try {
                const parsed = parseYaml(raw);
                if (parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
                    data = parsed as Record<string, unknown>;
                }
            } catch {
                // Malformed YAML — leave data as empty object; raw text is still available.
            }
            frontmatter = { raw, data };
            frontmatterBlock = fmMatch[0];
            body = content.slice(fmMatch[0].length);
        }

        // --- sections ---
        const hits = findHeadings(body, hashes);
        const first = hits[0];
        const preamble = first !== undefined ? body.slice(0, first.index) : body;
        const allSections: Section[] = hits.map((hit, idx) => {
            const next = hits[idx + 1];
            const end = next !== undefined ? next.index : body.length;
            return {
                name: hit.name,
                headingLine: hit.headingLine,
                originalText: body.slice(hit.index, end),
                modifiedText: null,
            };
        });

        // Deduplicate: keep the first occurrence of each section name, drop the
        // rest. Duplicate sections are a structural corruption (copy-paste error,
        // double-write, or agent body-that-includes-other-section-headings).
        // Recording the dropped names lets the CLI surface them as warnings so
        // the corruption is visible rather than silently healed.
        const seen = new Set<string>();
        const sections: Section[] = [];
        const duplicateNames: string[] = [];
        for (const s of allSections) {
            if (seen.has(s.name)) {
                duplicateNames.push(s.name);
            } else {
                seen.add(s.name);
                sections.push(s);
            }
        }

        const doc = new MarkdownDocument(domain, frontmatterBlock, frontmatter, preamble, sections);
        doc._duplicateSectionNames.push(...duplicateNames);
        return doc;
    }

    /** Domain kind passed to {@link parse}. */
    get domain(): MarkdownDomain {
        return this._domain;
    }

    /**
     * Replace the body preamble — everything between the frontmatter block and
     * the first `###` section heading. Sections and frontmatter are untouched.
     * Used by body-write operations (e.g. PATCH /tasks/{wbs}/body).
     */
    replacePreamble(newBody: string): void {
        this._preamble = newBody;
    }
    /** Parsed frontmatter, or `null` if the file has no frontmatter. */
    get frontmatter(): ParsedFrontmatter | null {
        return this._frontmatter;
    }

    /** Raw YAML text between the fences, or `null` if no frontmatter. */
    get frontmatterRaw(): string | null {
        return this._frontmatter?.raw ?? null;
    }

    /** Parsed frontmatter as a plain object, or `null` if no frontmatter. */
    get frontmatterData(): Record<string, unknown> | null {
        return this._frontmatter?.data ?? null;
    }

    /**
     * Return the full body WITHOUT the leading YAML frontmatter block.
     *
     * Returns the preamble + all sections serialized in order — everything
     * that follows the frontmatter fence. This is the content intended for
     * preview/editing; frontmatter values surface separately via
     * {@link frontmatterData}. In-body code fences are never touched.
     */
    get bodyWithoutFrontmatter(): string {
        let result = this._preamble;
        for (const section of this._sections) {
            result += section.modifiedText ?? section.originalText;
        }
        return result;
    }

    /** All section names present in the document (canonical and non-canonical). */
    get sectionNames(): string[] {
        return this._sections.map((s) => s.name);
    }

    /**
     * Same-level heading lines stripped from section bodies during mutations (R2).
     * Empty unless a `replaceSection`/`insertSection` body carried `###`/`##` lines.
     * The I/O boundary (CLI output seam) surfaces these as warnings; the document
     * layer stays pure and never writes to a console itself.
     */
    get strippedHeadings(): readonly string[] {
        return this._strippedHeadings;
    }

    /**
     * Section names that appeared more than once in the source markdown and were
     * dropped at parse time (keeping the first occurrence). Empty unless the file
     * was structurally corrupted. The CLI layer surfaces these as warnings so the
     * corruption is visible rather than silently self-healed.
     */
    get duplicateSectionNames(): readonly string[] {
        return this._duplicateSectionNames;
    }

    private get canonicalSections(): readonly string[] {
        return this._domain === 'task' ? TASK_CANONICAL_SECTIONS : FEATURE_CANONICAL_SECTIONS;
    }

    private validateSectionName(name: string): void {
        if (!this.canonicalSections.includes(name)) {
            throw new Error(
                `Unknown section "${name}" for domain "${this._domain}". ` +
                    `Canonical sections: ${this.canonicalSections.join(', ')}.`,
            );
        }
    }

    private findSection(name: string): Section | undefined {
        return this._sections.find((s) => s.name === name);
    }

    /** Returns `true` if a section with the given name exists in the document. */
    hasSection(name: string): boolean {
        return this.findSection(name) !== undefined;
    }

    /**
     * Get the body text of a named section.
     *
     * @param name - canonical section name (validated against the domain vocabulary)
     * @returns raw body text (everything after the heading line, including
     *   leading/trailing newlines), or `null` if the section doesn't exist
     */
    getSection(name: string): string | null {
        this.validateSectionName(name);
        const section = this.findSection(name);
        if (section === undefined) return null;
        const text = section.modifiedText ?? section.originalText;
        const newlineIdx = text.indexOf('\n');
        return newlineIdx === -1 ? '' : text.slice(newlineIdx + 1);
    }

    /**
     * Replace the body of a named section, **upserting** it when absent.
     *
     * The progressive-section lifecycle means a task gains sections as it moves
     * through statuses (e.g. `Solution` first appears at `wip`). Writing a section
     * that the file does not yet carry inserts it at its canonical position rather
     * than failing — so an agent can fill `Solution` without a separate "add
     * section" step. Existing sections are untouched (losslessness preserved).
     *
     * @param name - canonical section name (validated against the domain vocabulary)
     * @param body - new body text (everything that should follow the heading line)
     * @throws if the section name is not canonical
     */
    replaceSection(name: string, body: string): void {
        this.validateSectionName(name);
        const cleaned = this.stripSameLevelHeadings(body);
        const section = this.findSection(name);
        if (section !== undefined) {
            // Guarantee a trailing newline so the next section heading stays at
            // line-start; otherwise a body without one (or one whose final line
            // was a stripped same-level heading) fuses with the following
            // section's heading and swallows it on re-parse.
            const withTrailer = cleaned.endsWith('\n') ? cleaned : `${cleaned}\n`;
            section.modifiedText = `${section.headingLine}\n${withTrailer}`;
            return;
        }
        this.insertSection(name, cleaned);
    }

    /**
     * Strip same-level headings from a section body (self-heal, R2 / task 0115).
     *
     * A section body must never contain lines at the domain's heading level
     * (`###` for tasks, `##` for features) outside fenced code blocks — on
     * re-parse {@link findHeadings} would treat them as new sections, producing
     * phantom entries that fail the closed-world L2 check. Rather than throw on
     * the write hot path (which would force an agent regenerate+retry), this
     * removes the offending lines and warns, so the write self-heals.
     *
     * Code-fence state is tracked exactly as in {@link findHeadings}, so a
     * heading-shaped line inside a ``` block is content, not a heading, and is
     * preserved verbatim.
     *
     * Stripped lines are recorded on {@link strippedHeadings} so a caller at the
     * I/O boundary (the CLI output seam) can surface them — the document layer is
     * pure and never writes to a console/stderr itself.
     */
    private stripSameLevelHeadings(body: string): string {
        const prefix = `${'#'.repeat(HEADING_LEVELS[this._domain])} `;
        const lines = body.split('\n');
        const kept: string[] = [];
        let inCodeBlock = false;
        for (const line of lines) {
            if (line.startsWith('```')) {
                inCodeBlock = !inCodeBlock;
                kept.push(line);
                continue;
            }
            if (!inCodeBlock && line.startsWith(prefix)) {
                this._strippedHeadings.push(line);
                continue;
            }
            kept.push(line);
        }
        return kept.join('\n');
    }

    /**
     * Insert a brand-new canonical section at its position in the canonical order,
     * relative to the sections already present. Appends a trailing blank line so
     * the following section keeps its spacing.
     */
    private insertSection(name: string, body: string): void {
        const level = HEADING_LEVELS[this._domain];
        const headingLine = `${'#'.repeat(level)} ${name}`;
        const canonicalIndex = this.canonicalSections.indexOf(name);
        const newSection: Section = {
            name,
            headingLine,
            originalText: '',
            modifiedText: `${headingLine}\n\n${body.trimEnd()}\n\n`,
        };
        // Find the first existing section whose canonical rank is greater; insert before it.
        let at = this._sections.length;
        for (let i = 0; i < this._sections.length; i++) {
            const rank = this.canonicalSections.indexOf(this._sections[i]?.name ?? '');
            if (rank > canonicalIndex) {
                at = i;
                break;
            }
        }
        this._sections.splice(at, 0, newSection);
    }

    /**
     * Replace the auto-generated marker region within a named section.
     *
     * Finds the `<!-- AUTO-GENERATED -->` ... `<!-- END AUTO-GENERATED -->`
     * block and replaces its content (including markers) with the provided
     * content wrapped in standard markers. Text outside the markers is preserved.
     *
     * @param name - canonical section name
     * @param content - new content between the markers (table, list, etc.)
     * @throws if the section doesn't exist or has no marker region
     */
    replaceMarkerRegion(name: string, content: string): void {
        this.validateSectionName(name);
        const section = this.findSection(name);
        if (section === undefined) {
            throw new Error(`Section "${name}" does not exist in this document.`);
        }
        const text = section.modifiedText ?? section.originalText;
        const startMatch = MARKER_START_RE.exec(text);
        const endMatch = MARKER_END_RE.exec(text);
        if (startMatch === null || endMatch === null || startMatch.index >= endMatch.index) {
            throw new Error(`No marker region found in section "${name}".`);
        }
        const before = text.slice(0, startMatch.index);
        const after = text.slice(endMatch.index + endMatch[0].length);
        section.modifiedText = `${before}${START_MARKER}\n${content}\n${END_MARKER}${after}`;
    }

    /**
     * Set or replace a scalar field in the YAML frontmatter.
     *
     * Replaces the field's line in place when present, appends it to the end of
     * the frontmatter block when absent, and prepends a fresh frontmatter block
     * when the document has none. Untouched frontmatter lines are byte-preserved;
     * the operation is pure string assembly, so `$`-sequences (e.g. `$1`, `$&`)
     * in existing values are written verbatim.
     *
     * @param key - frontmatter key (matched at line start, before the first `:`)
     * @param value - scalar value to write after `<key>: `
     */
    setFrontmatterField(key: string, value: string): void {
        const fieldLine = `${key}: ${value}`;

        if (this._frontmatter === null) {
            const raw = fieldLine;
            this._frontmatter = { raw, data: { [key]: value } };
            this._frontmatterBlock = `---\n${raw}\n---\n\n`;
            return;
        }

        const oldRaw = this._frontmatter.raw;
        const lines = oldRaw.split('\n');
        const keyPrefix = `${key}:`;
        const idx = lines.findIndex((line) => line === keyPrefix || line.startsWith(`${keyPrefix} `));
        if (idx === -1) {
            lines.push(fieldLine);
        } else {
            lines[idx] = fieldLine;
        }
        const raw = lines.join('\n');
        this._frontmatter = { raw, data: { ...this._frontmatter.data, [key]: value } };
        // Swap only the raw YAML span inside the original fence block so the
        // opening fence, line-ending style, and trailer bytes stay untouched.
        const rawStart = this._frontmatterBlock.indexOf(oldRaw);
        this._frontmatterBlock =
            rawStart === -1
                ? `---\n${raw}\n---\n`
                : this._frontmatterBlock.slice(0, rawStart) +
                  raw +
                  this._frontmatterBlock.slice(rawStart + oldRaw.length);
    }

    /**
     * Serialize the document back to a string.
     *
     * Untouched sections round-trip byte-identically. Modified sections use
     * their replacement text. Frontmatter is output exactly as parsed.
     */
    serialize(): string {
        let result = this._frontmatterBlock;
        result += this._preamble;
        for (const section of this._sections) {
            result += section.modifiedText ?? section.originalText;
        }
        return result;
    }
}
