/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/domain/src/analytics/artifact-digest.ts (task 0669).
 */
export declare const ARTIFACT_ARRAY_CLASSIFICATION: Readonly<Record<string, 'ranked' | 'set'>>;
export declare const RANKED_ARTIFACT_KEYS: ReadonlySet<string>;
export declare function semanticArtifactDigest(artifactJson: unknown): string;
