/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/services/history-anatomy.ts (task 1005 R2).
 */
export declare interface CacheIdentity {
    contractVersion: string;
    mode: 'daily' | 'ad-hoc';
    date: string;
    timezone: string;
    bounds: { since: string; until: string };
    sources: string[];
}
export declare interface CacheProvenance {
    identity: CacheIdentity;
    windowState: 'provisional' | 'closed';
    generatedAt: string;
    validatedAt: string;
    artifactDigest: string;
    baselineArtifactDigest: string | null;
    contractDigest: string;
    skillDigest: string;
    workflowDigest: string;
    helperDigest: string;
    coverage: Array<{ source: string; status: string; lastImportedAt: string | null }>;
    runId?: string;
    currentArtifactPath?: string;
    baselineArtifactPath?: string | null;
    spurVersion?: string;
    schemaVersion?: number;
    executor?: string;
    model?: string;
    cacheDisposition?: CacheDisposition;
}
export declare type CacheDisposition = 'hit' | 'miss' | 'forced-recompute';
export declare interface CacheDecision {
    disposition: CacheDisposition;
    reasons: string[];
}
export declare const REPORT_SECTIONS: string[];
export declare const FINDING_FIELDS: string[];
export declare function semanticArtifactDigest(artifactJson: unknown): string;
export declare function parseProvenance(reportMarkdown: string): CacheProvenance | null;
export declare function decideCache(
    cached: CacheProvenance | null,
    current: CacheProvenance,
    opts: { recompute: boolean; dayClosed: boolean },
): CacheDecision;
export declare function checkReportStructure(reportMarkdown: string): { ok: boolean; problems: string[] };
export declare function logicDigest(path: string | undefined): string;
export declare function importedSnapshotAsOf(coverage: CacheProvenance['coverage']): string;
export declare function resolvePaths(opts: {
    helper: string;
    reportDir: string;
    date?: string;
    output?: string;
    now?: Date;
    tz?: string;
    mode?: string;
    since?: string;
    until?: string;
}): string;
export declare type SelectorValidation =
    | {
          ok: true;
          mode: 'daily' | 'ad-hoc';
          date: string | null;
          focus: string | null;
          since: string | null;
          until: string | null;
      }
    | { ok: false; errors: string[] };
export declare function validateSelector(opts: {
    mode?: string;
    date?: string;
    since?: string;
    until?: string;
    focus?: string;
    recompute?: string;
    output?: string;
}): SelectorValidation;
export declare interface ProbeOptions {
    artifact: string;
    target: string;
    baseline?: string;
    mode: 'daily' | 'ad-hoc';
    date?: string;
    recompute: boolean;
    executor?: string;
    model?: string;
    skillDir?: string;
    contractFile?: string;
    workflowFile?: string;
    helperFile?: string;
    contractVersion?: string;
    runId?: string;
    spurVersion?: string;
    now?: Date;
}
export declare function buildProvenance(opts: ProbeOptions): CacheProvenance;
export declare function probe(opts: ProbeOptions): { decision: CacheDecision; current: CacheProvenance };
export declare function renderProvenanceFrontmatter(p: CacheProvenance): string;
export declare function bannerLine(p: CacheProvenance): string;
export declare function stampReport(candidateMarkdown: string, p: CacheProvenance): string;
export declare function refreshReport(publishedMarkdown: string, validatedAt: string, disposition: CacheDisposition): string;
export declare function publishAtomically(candidatePath: string, targetPath: string): void;
export declare interface CacheCliResult {
    exitCode: number;
    stdout: string;
    stderr: string;
}
export declare function porcelainPaths(text: string): Set<string>;
export declare function diffPorcelain(before: string, now: string, expects: Set<string>): string[];
