/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/workflow/idea-handoff-cli.ts (task 0824).
 */
export declare interface IdeaHandoffCliEnv {
    __runId?: string;
    featureId?: string;
    spurBin?: string;
}
export declare interface IdeaHandoffCliOutcome {
    exitCode: number;
    result?: unknown;
}
export declare function runIdeaHandoffCli(
    env: IdeaHandoffCliEnv,
    run?: (input: { runId: string; featureId: string; spurBin: string }) => Promise<unknown>,
): Promise<IdeaHandoffCliOutcome>;
