/** GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit. Requires Bun for SQLite. */
export declare const createOrAttachInlineRun: typeof import('@gobing-ai/spur-app').createOrAttachInlineRun;
export declare const openInlineRunProjectDb: typeof import('@gobing-ai/spur-app').openInlineRunProjectDb;
export declare const computeProofInputFingerprint: typeof import('@gobing-ai/spur-app').computeProofInputFingerprint;
export declare const readProofInputContents: typeof import('@gobing-ai/spur-app').readProofInputContents;
export declare const createWorkflowActionTraceWriter: typeof import('@gobing-ai/spur-app').createWorkflowActionTraceWriter;
export declare const EMBEDDED_SPUR_SCHEMAS: ReadonlyMap<string, string>;
export declare function splitLaunchCommand(value: string, label: string): { command: string; leadingArgs: string[] } | { error: string };
