/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/workflow/plan-projection.ts (task 1104).
 */
export declare interface PhasedPlanItem {
    label: string;
    id: string;
    outcome: 'pending' | 'active' | 'completed' | 'skipped' | 'failed' | 'blocked' | 'unattempted';
    note?: string;
    text: string;
    parent?: string;
    title?: string;
}
export declare interface BatchTask {
    wbs: string;
    name: string;
}
export declare function planLetter(index: number): string;
export declare function planChild(parent: string, index: number): string;
export declare function buildPhasedPlan(def: unknown): PhasedPlanItem[] | null;
export declare function validatePhaseTable(def: unknown): string[];
export declare function insertOnEntry(items: PhasedPlanItem[], stateId: string, def: unknown): PhasedPlanItem[];
export declare function buildBatchPlan(tasks: BatchTask[]): PhasedPlanItem[][];
export declare function taskPhaseChildren(taskLetter: string, plan: PhasedPlanItem[]): PhasedPlanItem[];
export declare function hostStatus(
    outcome: 'pending' | 'active' | 'completed' | 'skipped' | 'failed' | 'blocked' | 'unattempted',
): 'completed' | 'in_progress' | 'pending';
export declare function hostText(item: PhasedPlanItem): string;
