/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/services/quality-gate.ts (task 1006 R1).
 */
export declare const MAX_GATE_ATTEMPTS: number;
export declare const MAX_FINDINGS: number;
export declare const RETRY_DELAY_MS_DEFAULT: number;
export declare const RETRY_DELAY_MS_ENV: string;
export declare const LOCKED_PATTERN: RegExp;
export declare const FINDINGS_PATTERN: RegExp;
export declare const COVERAGE_ROW_PATTERN: RegExp;
export declare const RECEIPT_SCHEMA_VERSION: 'check-receipt/v1';
export declare const GATE_LOCK_DIR_ENV: string;
export declare const GATE_LOCK_POLL_MS_ENV: string;
export declare const GATE_LOCK_OFF_ENV: string;
export declare const GATE_LOCK_TOKEN_ENV: string;
export declare const GATE_LOCK_POLL_MS_DEFAULT: number;
export declare const GATE_LOCK_MKDIR_HOLD_MS_ENV: string;
export declare interface GateLock {
    release(): void;
    queueWaitMs: number;
    token: string;
}
export declare function acquireGateLock(env: QualityGateEnv, logLine?: (line: string) => void): GateLock;
export declare interface QualityGateEnv {
    wbs: string;
    qualityGateCmd?: string;
    gateProbeCmd?: string;
    proofDigest?: string;
    runId?: string;
    [key: string]: string | undefined;
}
export declare interface QualityGateOptions {
    cwd?: string;
    recomputeFingerprint?: (
        cwd: string,
        env: QualityGateEnv,
    ) => { ok: true; digest: string } | { ok: false; error: string };
}
export declare interface QualityGateResult {
    status: 'PASS' | 'FAIL';
    attempts: number;
    logFile: string;
    findingsFile: string;
    statusFile: string;
    attemptFile: string;
    receiptFile?: string;
}
export declare function isTransientLock(attemptOutput: string): boolean;
export declare function extractFindings(logText: string): string;
export declare function tailLines(text: string, count: number): string;
export declare function retryMessage(attempt: number): string;
export declare interface CoverageThreshold {
    functions?: number;
    lines?: number;
}
export declare function parseCoverageThreshold(bunfigText: string): CoverageThreshold | null;
export declare function scanCoverageShortfalls(logText: string, threshold: CoverageThreshold): string[];
export declare type ReceiptTier = 'full' | 'light';
export declare type CheckStatus = 'PASS' | 'FAIL';
export declare type ReceiptReuseReason = 'missing' | 'failed' | 'stale' | 'light-only';
export declare interface CheckReceiptRow {
    id: string;
    cmd: string;
    status: CheckStatus;
    durationMs: number;
    logPath: string;
}
export declare interface CheckReceipt {
    schemaVersion: 'check-receipt/v1';
    wbs: string;
    runId: string;
    tier: ReceiptTier;
    inputDigest: string;
    checks: CheckReceiptRow[];
    status: CheckStatus;
    completedAt: string;
}
export declare interface ReceiptReadStatus {
    reuse: boolean;
    reason: ReceiptReuseReason | 'ok';
}
export declare interface BuildReceiptInput {
    wbs: string;
    runId: string;
    tier: ReceiptTier;
    inputDigest: string;
    checks: CheckReceiptRow[];
    completedAt: string;
}
export declare function buildReceipt(input: BuildReceiptInput): CheckReceipt;
export declare function receiptFailsAtDigest(receipt: CheckReceipt | null, currentDigest: string): boolean;
export declare function readReceiptStatus(receiptPath: string, currentDigest: string): ReceiptReadStatus;
export declare interface ReceiptReuseDecision {
    reuse: boolean;
    receiptStatus: ReceiptReadStatus;
    refusal?: string;
    recomputedDigest?: string;
}
export declare function resolveReceiptReuse(
    receiptPath: string,
    env: QualityGateEnv,
    cwd: string,
    recomputeFn?: (
        cwd: string,
        env: QualityGateEnv,
    ) => { ok: true; digest: string } | { ok: false; error: string },
): ReceiptReuseDecision;
export declare function recomputeGateProofFingerprint(
    cwd: string,
    env: QualityGateEnv,
): { ok: true; digest: string } | { ok: false; error: string };
export declare interface LightScope {
    files: string[];
    workspaces: string[];
    tests: string[];
}
export declare function lightScope(changedFiles: string[], exists?: (p: string) => boolean): LightScope;
export declare function shQuote(arg: string): string;
export declare interface LightCheckPlan {
    id: string;
    cmd: string;
}
export declare function workspaceHasTypecheck(workspace: string): boolean;
export declare function planLightChecks(scope: LightScope, hasTypecheck?: (workspace: string) => boolean): LightCheckPlan[];
export declare interface LightGateResult {
    status: CheckStatus;
    scope: LightScope;
    checks: CheckReceiptRow[];
    logFile: string;
    receiptFile: string;
}
export declare function runLightGate(env: QualityGateEnv, options?: QualityGateOptions): LightGateResult;
export declare interface DeferredGateResult {
    status: 'DEFERRED' | 'FAIL';
    light: LightGateResult;
    statusFile: string;
}
export declare function runDeferredGate(env: QualityGateEnv, options?: QualityGateOptions): DeferredGateResult;
export declare function runShellCommand(
    cmd: string,
    cwd: string | undefined,
    extraEnv?: Record<string, string>,
): { output: string; code: number };
export declare function runQualityGate(
    mode: 'run' | 'recheck',
    env: QualityGateEnv,
    options?: QualityGateOptions,
): QualityGateResult;
