/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/services/residual-scan.ts (task 1003 R5).
 */
export declare type ResidualCategory = 'review-finding' | 'diff-marker' | 'unchecked-box' | 'staging-residue';
export declare type ResidualClass = 'blocking' | 'deferrable' | 'advisory' | 'housekeeping';
export declare interface ResidualItem {
    id: string;
    category: ResidualCategory;
    class: ResidualClass;
    priority?: string;
    location: string;
    text: string;
}
export declare interface ResidualArtifact {
    wbs: string;
    base: string | null;
    scanned: Record<ResidualCategory, boolean>;
    items: ResidualItem[];
    counts: { blocking: number; deferrable: number; advisory: number; housekeeping: number };
}
export declare interface Deferral {
    id: string;
    reason: string;
}
export declare interface ResidualScanInputs {
    wbs: string;
    base: string | null;
    taskContent: string;
    addedLines: Array<{ file: string; line: number; text: string }>;
    stagingResidue: string[];
    deferrals: Deferral[];
}
export declare interface FoldResult {
    verdict: 'PASS' | 'PARTIAL' | 'FAIL';
    checks: Array<{ name: string; status: string; evidence: string }>;
    findings: string;
}
export declare const ALLOW_PRAGMA: 'residual-scan:allow';
export declare function recordedVerdictPath(runDir: string, wbs: string, fs: Pick<typeof import('node:fs'), 'lstatSync' | 'existsSync'>): string;
export declare function makeItemId(category: ResidualCategory, location: string, text: string): string;
export declare function normalizeAnchor(location: string): string;
export declare function locationOf(locationCell: string, finding: string): string;
export declare function parseReviewFindings(
    taskContent: string,
): Array<{ priority: string; location: string; text: string; deferral?: string }>;
export declare function parseDiffMarkers(
    addedLines: Array<{ file: string; line: number; text: string }>,
): Array<{ location: string; text: string }>;
export declare function findUncheckedBoxes(taskContent: string): Array<{ location: string; text: string }>;
export declare function classify(
    items: Array<Omit<ResidualItem, 'id' | 'class'> & { category: ResidualCategory }>,
    deferrals: Deferral[],
): ResidualItem[];
export declare function scanResiduals(inputs: ResidualScanInputs): ResidualArtifact;
export declare function blockingAnchors(items: ResidualItem[]): string[];
export declare function foldVerdict(
    verdict: { verdict: string; checks: Array<{ name: string; status: string; evidence: string }> },
    scan: ResidualArtifact,
    existingFindings: string,
    maxFindings?: number,
): FoldResult;
export declare function renderReport(wbs: string, items: ResidualItem[], attemptCount: number): string;
