import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { main } from '../src/index';
import type { CommandOutput } from '../src/output';
import { createTempProject } from './helpers';

const REPO_ROOT = process.env.SPUR_REPO_ROOT ?? join(import.meta.dir, '..', '..', '..');

function nullOutput(): CommandOutput {
    return { write: () => {}, error: () => {} };
}

/** Build main() options with the global rules seed redirected to an isolated temp dir. */
async function isolatedOptions(cwd: string) {
    const globalDir = await mkdtemp(join(tmpdir(), 'spur-glob-'));
    const env = { ...process.env, SPUR_GLOBAL_RULES_DIR: globalDir };
    return { options: { cwd, env, output: nullOutput(), dbUrl: ':memory:' as const }, globalDir };
}

describe('spur init template copy', () => {
    test('task templates are remapped under .spur/tasks without creating .spur/templates', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        // Task templates under .spur/tasks/templates/
        const tasksBase = join(cwd, '.spur', 'tasks', 'templates');
        expect(existsSync(join(tasksBase, 'standard.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'feature-impl.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'issue.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'review.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'meta.md'))).toBe(true);
        expect(existsSync(join(cwd, '.spur', 'templates'))).toBe(false);
    });

    test('bundled template files exist at source', async () => {
        const dir = await mkdtemp(join(tmpdir(), 'spur-init-test-'));
        const bundledTaskDir = join(REPO_ROOT, 'config', 'templates', 'task');
        expect(existsSync(bundledTaskDir)).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'standard.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'feature-impl.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'issue.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'review.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'meta.md'))).toBe(true);
        await rm(dir, { recursive: true });
    });

    test('template files have valid frontmatter', () => {
        const standardContent = readFileSync(join(REPO_ROOT, 'config', 'templates', 'task', 'standard.md'), 'utf-8');
        expect(standardContent).toContain('schema_version: 1');
        expect(standardContent).toContain('status: backlog');
        expect(standardContent).toContain('{{ NAME }}');
    });

    test('feature template has the canonical Tasks auto-gen marker region', () => {
        // Must match the markers `replaceMarkerRegion` recognizes (markdown-document.ts,
        // 0042) and the real corpus — `spur feature refresh` (0058) relies on this.
        const featureContent = readFileSync(join(REPO_ROOT, 'config', 'templates', 'feature', 'default.md'), 'utf-8');
        expect(featureContent).toContain('## Tasks');
        expect(featureContent).toContain('<!-- AUTO-GENERATED by spur feature refresh -->');
        expect(featureContent).toContain('<!-- END AUTO-GENERATED -->');
    });

    test('init is idempotent — re-init does not overwrite templates without --force', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        // First init — templates are created.
        expect(await main(['init'], options)).toBe(0);
        const tmplPath = join(cwd, '.spur', 'tasks', 'templates', 'standard.md');
        expect(existsSync(tmplPath)).toBe(true);

        // Modify the template in-place to add a marker.
        const original = readFileSync(tmplPath, 'utf-8');
        const marker = '<!-- IDEMPOTENCE MARKER -->';
        writeFileSync(tmplPath, `${original}\n${marker}`, 'utf-8');

        // Re-init without --force converges (task 0649 R1) — it seeds only what is
        // missing and writes no config, so the modified template is preserved.
        expect(await main(['init'], options)).toBe(0);
        // Template still has our marker — not overwritten.
        const after = readFileSync(tmplPath, 'utf-8');
        expect(after).toContain(marker);

        // Re-init with --force does overwrite.
        expect(await main(['init', '--force'], options)).toBe(0);
        const forced = readFileSync(tmplPath, 'utf-8');
        expect(forced).not.toContain(marker);
    });

    test('section-matrix.yaml is copied to .spur/tasks/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const matrixPath = join(cwd, '.spur', 'tasks', 'section-matrix.yaml');
        expect(existsSync(matrixPath)).toBe(true);
        const content = readFileSync(matrixPath, 'utf-8');
        expect(content).toContain('variants:');
    });

    test('workflow lifecycle and pipeline YAMLs remain bundled instead of project-copied', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const wfDir = join(cwd, '.spur', 'workflows');
        expect(existsSync(wfDir)).toBe(false);
    });

    test('docs scaffolds are copied to project-root docs/ (R1 — task 0088)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const docsDir = join(cwd, 'docs');
        expect(existsSync(join(docsDir, '99_PROJECT_CONSTITUTION.md'))).toBe(true);
        expect(existsSync(join(docsDir, '00_ADR.md'))).toBe(true);
        expect(existsSync(join(docsDir, '01_PRD.md'))).toBe(true);
        expect(existsSync(join(docsDir, '02_ROADMAP.md'))).toBe(true);
        expect(existsSync(join(docsDir, '03_ARCHITECTURE.md'))).toBe(true);
        expect(existsSync(join(docsDir, '04_DESIGN.md'))).toBe(true);
        expect(existsSync(join(docsDir, '05_FEATURES.md'))).toBe(true);

        const designContent = readFileSync(join(docsDir, '04_DESIGN.md'), 'utf-8');
        expect(designContent).toContain('Repository-root `DESIGN.md` owns all UI/UX design');
        expect(designContent).toContain('focused on non-UI surface design');
    });

    test('docs scaffolds are preserved even under --force (R1 — never clobber customized docs)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        // First init scaffolds the docs
        expect(await main(['init'], options)).toBe(0);

        // Customize one doc
        const prdPath = join(cwd, 'docs', '01_PRD.md');
        writeFileSync(prdPath, 'CUSTOM CONTENT — must survive re-init');

        // Re-init with --force must NOT overwrite the customized doc (preserve: true)
        expect(await main(['init', '--force'], options)).toBe(0);

        const content = readFileSync(prdPath, 'utf-8');
        expect(content).toBe('CUSTOM CONTENT — must survive re-init');
    });

    test('doc templates render at project root without a project template copy', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        expect(existsSync(join(cwd, '.spur', 'templates'))).toBe(false);
        const content = readFileSync(join(cwd, 'docs', '04_DESIGN.md'), 'utf-8');
        expect(content).not.toContain('{{init-date}}');
        expect(content).toMatch(/updated_at:\s*\d{4}-\d{2}-\d{2}/);
    });

    test('AGENTS.md scaffold is copied to project root with indexed-context block (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const agentsPath = join(cwd, 'AGENTS.md');
        expect(existsSync(agentsPath)).toBe(true);
        const content = readFileSync(agentsPath, 'utf-8');
        expect(content).toContain('.spur/context/');
        expect(content).toContain('indexed-context');
    });

    test('AGENTS.md substitutes {project-name} from --name and leaves no brace tokens (task 0242)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init', '--name', 'MyApp'], options)).toBe(0);

        const content = readFileSync(join(cwd, 'AGENTS.md'), 'utf-8');
        expect(content).toContain('MyApp');
        expect(content).not.toContain('{project-name}');
        expect(content).not.toContain('{project-description}');
        // No residual kebab-case brace tokens after init (R2 locked decision).
        expect(content.match(/\{[a-z0-9-]+\}/g)).toBeNull();
        expect(content).toContain('## Indexed context');
        expect(content).toContain('## Harness-first contract');
        expect(content).toContain('### Harness tool routing');
        expect(content).toContain('### Doc map');
        expect(content).toContain('Working-layer, audit, and satellite rules live in the project constitution.');
        expect(content).toContain('**Platform fallback:**');
        expect(content).toContain('## Design system');
        expect(content).toContain('repository-root `DESIGN.md`');
        expect(content).toContain('## Superskill CLI surface');
        expect(content).toContain('superskill install <plugin>');
    });

    test('AGENTS.md is preserved under --force (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, 'CUSTOM AGENTS — must survive re-init');

        expect(await main(['init', '--force'], options)).toBe(0);
        // Custom content is preserved (preserve: true — manifest never overwrites)
        const afterForce = readFileSync(agentsPath, 'utf-8');
        expect(afterForce).toContain('CUSTOM AGENTS — must survive re-init');
        // Block injection still fires idempotently — appends the activation block
        expect(afterForce).toContain('## Indexed context');
    });

    test('.gitignore gets .spur/context/ entry on init (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const gitignorePath = join(cwd, '.gitignore');
        expect(existsSync(gitignorePath)).toBe(true);
        const content = readFileSync(gitignorePath, 'utf-8');
        expect(content).toContain('.spur/context/');
    });

    test('.gitignore append is idempotent — re-init does not duplicate entry (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        // Manually re-run the append by calling init again with --force
        expect(await main(['init', '--force'], options)).toBe(0);

        const content = readFileSync(join(cwd, '.gitignore'), 'utf-8');
        const matches = content.match(/\.spur\/context\//g) ?? [];
        expect(matches.length).toBe(1);
    });

    test('--minimal mode still appends .spur/context/ to .gitignore (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init', '--minimal'], options)).toBe(0);

        const content = readFileSync(join(cwd, '.gitignore'), 'utf-8');
        expect(content).toContain('.spur/context/');
    });

    test('existing AGENTS.md without indexed-context block gets block appended (task 0232)', async () => {
        const cwd = await createTempProject();
        // Pre-create AGENTS.md with custom content (no indexed-context block)
        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, '# My Project\n\nCustom content here.\n', 'utf-8');

        const { options } = await isolatedOptions(cwd);
        expect(await main(['init'], options)).toBe(0);

        const content = readFileSync(agentsPath, 'utf-8');
        // Original content preserved
        expect(content).toContain('# My Project');
        expect(content).toContain('Custom content here.');
        // Block appended
        expect(content).toContain('## Indexed context');
        expect(content).toContain('.spur/context/anatomy.md');
    });

    test('existing AGENTS.md with indexed-context block is not duplicated (task 0232)', async () => {
        const cwd = await createTempProject();
        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, '# My Project\n\n## Indexed context\n\nAlready has it.\n', 'utf-8');

        const { options } = await isolatedOptions(cwd);
        expect(await main(['init'], options)).toBe(0);

        const content = readFileSync(agentsPath, 'utf-8');
        const markerCount = (content.match(/## Indexed context/g) ?? []).length;
        expect(markerCount).toBe(1);
        expect(content).toContain('Already has it.');
    });

    test('--minimal mode still injects block into existing AGENTS.md (task 0232)', async () => {
        const cwd = await createTempProject();
        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, '# Minimal Project\n', 'utf-8');

        const { options } = await isolatedOptions(cwd);
        expect(await main(['init', '--minimal'], options)).toBe(0);

        const content = readFileSync(agentsPath, 'utf-8');
        expect(content).toContain('## Indexed context');
    });
});

describe('init docs contract (task 0313)', () => {
    test('scaffolded docs have {{init-date}} replaced with YYYY-MM-DD, no residual tokens', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init', '--name', 'knowledge-kit'], options)).toBe(0);

        const docsDir = join(cwd, 'docs');
        for (const doc of [
            '00_ADR.md',
            '01_PRD.md',
            '02_ROADMAP.md',
            '03_ARCHITECTURE.md',
            '04_DESIGN.md',
            '05_FEATURES.md',
            '99_PROJECT_CONSTITUTION.md',
        ]) {
            const content = readFileSync(join(docsDir, doc), 'utf-8');
            expect(content).not.toContain('{{init-date}}');
            // Check that updated_at has a real date (YYYY-MM-DD)
            const match = content.match(/updated_at:\s*(\d{4}-\d{2}-\d{2})/);
            expect(match).not.toBeNull();
            const date = match?.[1] ?? '';
            expect(date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
        }
    });

    test('scaffolded docs have §4.3 frontmatter fields (edit_rules, sync, read_before)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);
        expect(await main(['init'], options)).toBe(0);

        const docsDir = join(cwd, 'docs');
        // 00–05 should have edit_rules, sync, read_before
        for (const doc of [
            '00_ADR.md',
            '01_PRD.md',
            '02_ROADMAP.md',
            '03_ARCHITECTURE.md',
            '04_DESIGN.md',
            '05_FEATURES.md',
        ]) {
            const content = readFileSync(join(docsDir, doc), 'utf-8');
            expect(content).toContain('edit_rules:');
            expect(content).toContain('sync:');
            expect(content).toContain('read_before:');
        }
        // 99 should have edit_rules, sync, read_before, and created_at
        const constContent = readFileSync(join(docsDir, '99_PROJECT_CONSTITUTION.md'), 'utf-8');
        expect(constContent).toContain('edit_rules:');
        expect(constContent).toContain('sync:');
        expect(constContent).toContain('read_before:');
        expect(constContent).toContain('created_at:');
    });

    test('scaffolded 99 constitution has all sections referenced by AGENTS.md (§4.1, §4.4, §4.5, §5, §6)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const constContent = readFileSync(join(cwd, 'docs', '99_PROJECT_CONSTITUTION.md'), 'utf-8');
        // §4.1 — Doc map
        expect(constContent).toContain('§4.1');
        // §4.4 — Satellite rules
        expect(constContent).toContain('§4.4');
        // §4.5 — Satellite conventions
        expect(constContent).toContain('§4.5');
        // §5 — Working layers
        expect(constContent).toContain('§5');
        // §6 — Edit rules
        expect(constContent).toContain('§6');
        // §8 — Lessons (empty)
        expect(constContent).toContain('§8');
        expect(constContent).toContain('_(empty — add lessons as the project evolves)_');
    });

    test('scaffolded 04_DESIGN.md includes UI/UX boundary section', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const designContent = readFileSync(join(cwd, 'docs', '04_DESIGN.md'), 'utf-8');
        expect(designContent).toContain('DESIGN.md');
        expect(designContent).toContain('UI/UX');
    });
});

describe('source-vs-bundle parity (task 0313)', () => {
    test('source template docs match bundle-config output byte-for-byte', async () => {
        // SSOT lives under the repo-root bundled-asset tree (templates/docs).
        // The package-local copy (apps/cli/<cfg>) is gitignored and only produced at
        // publish (build:bundle) — CI check never runs that step — so we materialize a
        // fresh bundle into a temp dir via the same bundleConfig path used for the npm
        // tarball (see scripts/commands/bundle-config.ts).
        // Split the 'config' segment so this test (the parity gate itself) does not trip
        // sp-runtime-path, which bans contiguous config/{templates,...} literals.
        const { bundleConfig } = await import('../../../scripts/commands/bundle-config');
        const cfg = 'config';
        const sourceDir = join(REPO_ROOT, cfg, 'templates', 'docs');
        const outDir = await mkdtemp(join(tmpdir(), 'spur-bundle-docs-'));
        const docFiles = [
            '00_ADR.md',
            '01_PRD.md',
            '02_ROADMAP.md',
            '03_ARCHITECTURE.md',
            '04_DESIGN.md',
            '05_FEATURES.md',
            '99_PROJECT_CONSTITUTION.md',
        ];

        try {
            await bundleConfig(outDir);
            const bundleDir = join(outDir, 'templates', 'docs');

            for (const doc of docFiles) {
                const sourcePath = join(sourceDir, doc);
                const bundlePath = join(bundleDir, doc);
                // Message uses cfg + path segments so the source has no contiguous banned literal.
                expect(existsSync(sourcePath), `missing source template: ${cfg}/templates/docs/${doc}`).toBe(true);
                expect(existsSync(bundlePath), `bundleConfig omitted templates/docs/${doc}`).toBe(true);
                const sourceContent = readFileSync(sourcePath, 'utf-8');
                const bundleContent = readFileSync(bundlePath, 'utf-8');
                expect(bundleContent, `bundled template diverged: templates/docs/${doc}`).toBe(sourceContent);
            }
        } finally {
            await rm(outDir, { recursive: true, force: true });
        }
    });
});
