import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { main } from '../src/index';
import type { CommandOutput } from '../src/output';
import { createTempProject } from './helpers';

const REPO_ROOT = process.env.SPUR_REPO_ROOT ?? join(import.meta.dir, '..', '..', '..');

function nullOutput(): CommandOutput {
    return { write: () => {}, error: () => {} };
}

/** Build main() options with the global rules seed redirected to an isolated temp dir. */
async function isolatedOptions(cwd: string) {
    const globalDir = await mkdtemp(join(tmpdir(), 'spur-glob-'));
    const env = { ...process.env, SPUR_GLOBAL_RULES_DIR: globalDir };
    return { options: { cwd, env, output: nullOutput(), dbUrl: ':memory:' as const }, globalDir };
}

describe('spur init template copy', () => {
    test('templates are copied to .spur/tasks/templates/ and .spur/templates/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        // Task templates under .spur/tasks/templates/
        const tasksBase = join(cwd, '.spur', 'tasks', 'templates');
        expect(existsSync(join(tasksBase, 'standard.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'feature-impl.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'issue.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'review.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'meta.md'))).toBe(true);
        // Feature and BDD templates under .spur/templates/
        const templatesBase = join(cwd, '.spur', 'templates');
        expect(existsSync(join(templatesBase, 'feature', 'default.md'))).toBe(true);
        expect(existsSync(join(templatesBase, 'bdd', 'gherkin.md'))).toBe(true);
        expect(existsSync(join(templatesBase, 'bdd', 'checklist.md'))).toBe(true);
    });

    test('bundled template files exist at source', async () => {
        const dir = await mkdtemp(join(tmpdir(), 'spur-init-test-'));
        const bundledTaskDir = join(REPO_ROOT, 'config', 'templates', 'task');
        expect(existsSync(bundledTaskDir)).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'standard.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'feature-impl.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'issue.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'review.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'meta.md'))).toBe(true);
        await rm(dir, { recursive: true });
    });

    test('template files have valid frontmatter', () => {
        const standardContent = readFileSync(join(REPO_ROOT, 'config', 'templates', 'task', 'standard.md'), 'utf-8');
        expect(standardContent).toContain('schema_version: 1');
        expect(standardContent).toContain('status: backlog');
        expect(standardContent).toContain('{{ NAME }}');
    });

    test('feature template has the canonical Tasks auto-gen marker region', () => {
        // Must match the markers `replaceMarkerRegion` recognizes (markdown-document.ts,
        // 0042) and the real corpus — `spur feature refresh` (0058) relies on this.
        const featureContent = readFileSync(join(REPO_ROOT, 'config', 'templates', 'feature', 'default.md'), 'utf-8');
        expect(featureContent).toContain('## Tasks');
        expect(featureContent).toContain('<!-- AUTO-GENERATED by spur feature refresh -->');
        expect(featureContent).toContain('<!-- END AUTO-GENERATED -->');
    });

    test('init is idempotent — re-init does not overwrite templates without --force', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        // First init — templates are created.
        expect(await main(['init'], options)).toBe(0);
        const tmplPath = join(cwd, '.spur', 'tasks', 'templates', 'standard.md');
        expect(existsSync(tmplPath)).toBe(true);

        // Modify the template in-place to add a marker.
        const original = readFileSync(tmplPath, 'utf-8');
        const marker = '<!-- IDEMPOTENCE MARKER -->';
        writeFileSync(tmplPath, `${original}\n${marker}`, 'utf-8');

        // Re-init without --force is blocked (config.yaml already exists).
        expect(await main(['init'], options)).toBe(1);
        // Template still has our marker — not overwritten.
        const after = readFileSync(tmplPath, 'utf-8');
        expect(after).toContain(marker);

        // Re-init with --force does overwrite.
        expect(await main(['init', '--force'], options)).toBe(0);
        const forced = readFileSync(tmplPath, 'utf-8');
        expect(forced).not.toContain(marker);
    });

    test('section-matrix.yaml is copied to .spur/tasks/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const matrixPath = join(cwd, '.spur', 'tasks', 'section-matrix.yaml');
        expect(existsSync(matrixPath)).toBe(true);
        const content = readFileSync(matrixPath, 'utf-8');
        expect(content).toContain('variants:');
    });

    test('workflow lifecycle and pipeline YAMLs are copied to .spur/workflows/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const wfDir = join(cwd, '.spur', 'workflows');
        expect(existsSync(join(wfDir, 'task-lifecycle.yaml'))).toBe(true);
        expect(existsSync(join(wfDir, 'feature-lifecycle.yaml'))).toBe(true);
        expect(existsSync(join(wfDir, 'task-pipeline.yaml'))).toBe(true);
        expect(existsSync(join(wfDir, 'planning-pipeline.yaml'))).toBe(true);
    });

    test('docs scaffolds are copied to project-root docs/ (R1 — task 0088)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const docsDir = join(cwd, 'docs');
        expect(existsSync(join(docsDir, '99_PROJECT_CONSTITUTION.md'))).toBe(true);
        expect(existsSync(join(docsDir, '00_ADR.md'))).toBe(true);
        expect(existsSync(join(docsDir, '01_PRD.md'))).toBe(true);
        expect(existsSync(join(docsDir, '02_ROADMAP.md'))).toBe(true);
        expect(existsSync(join(docsDir, '03_ARCHITECTURE.md'))).toBe(true);
        expect(existsSync(join(docsDir, '04_DESIGN.md'))).toBe(true);
        expect(existsSync(join(docsDir, '05_FEATURES.md'))).toBe(true);
    });

    test('docs scaffolds are preserved even under --force (R1 — never clobber customized docs)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        // First init scaffolds the docs
        expect(await main(['init'], options)).toBe(0);

        // Customize one doc
        const prdPath = join(cwd, 'docs', '01_PRD.md');
        writeFileSync(prdPath, 'CUSTOM CONTENT — must survive re-init');

        // Re-init with --force must NOT overwrite the customized doc (preserve: true)
        expect(await main(['init', '--force'], options)).toBe(0);

        const content = readFileSync(prdPath, 'utf-8');
        expect(content).toBe('CUSTOM CONTENT — must survive re-init');
    });

    test('doc templates are also copied to .spur/templates/docs/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const tmplDir = join(cwd, '.spur', 'templates', 'docs');
        expect(existsSync(join(tmplDir, '99_PROJECT_CONSTITUTION.md'))).toBe(true);
        expect(existsSync(join(tmplDir, '00_ADR.md'))).toBe(true);
        expect(existsSync(join(tmplDir, '05_FEATURES.md'))).toBe(true);
    });
});
