import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { main } from '../src/index';
import type { CommandOutput } from '../src/output';
import { createTempProject } from './helpers';

const REPO_ROOT = process.env.SPUR_REPO_ROOT ?? join(import.meta.dir, '..', '..', '..');

function nullOutput(): CommandOutput {
    return { write: () => {}, error: () => {} };
}

/** Build main() options with the global rules seed redirected to an isolated temp dir. */
async function isolatedOptions(cwd: string) {
    const globalDir = await mkdtemp(join(tmpdir(), 'spur-glob-'));
    const env = { ...process.env, SPUR_GLOBAL_RULES_DIR: globalDir };
    return { options: { cwd, env, output: nullOutput(), dbUrl: ':memory:' as const }, globalDir };
}

describe('spur init template copy', () => {
    test('templates are copied to .spur/templates/task/ and .spur/templates/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        // Task templates under .spur/templates/task/
        const tasksBase = join(cwd, '.spur', 'tasks', 'templates');
        expect(existsSync(join(tasksBase, 'standard.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'feature-impl.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'issue.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'review.md'))).toBe(true);
        expect(existsSync(join(tasksBase, 'meta.md'))).toBe(true);
        // Feature and BDD templates under .spur/templates/
        const templatesBase = join(cwd, '.spur', 'templates');
        expect(existsSync(join(templatesBase, 'feature', 'default.md'))).toBe(true);
        expect(existsSync(join(templatesBase, 'bdd', 'gherkin.md'))).toBe(true);
        expect(existsSync(join(templatesBase, 'bdd', 'checklist.md'))).toBe(true);
    });

    test('bundled template files exist at source', async () => {
        const dir = await mkdtemp(join(tmpdir(), 'spur-init-test-'));
        const bundledTaskDir = join(REPO_ROOT, 'config', 'templates', 'task');
        expect(existsSync(bundledTaskDir)).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'standard.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'feature-impl.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'issue.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'review.md'))).toBe(true);
        expect(existsSync(join(bundledTaskDir, 'meta.md'))).toBe(true);
        await rm(dir, { recursive: true });
    });

    test('template files have valid frontmatter', () => {
        const standardContent = readFileSync(join(REPO_ROOT, 'config', 'templates', 'task', 'standard.md'), 'utf-8');
        expect(standardContent).toContain('schema_version: 1');
        expect(standardContent).toContain('status: backlog');
        expect(standardContent).toContain('{{ NAME }}');
    });

    test('feature template has the canonical Tasks auto-gen marker region', () => {
        // Must match the markers `replaceMarkerRegion` recognizes (markdown-document.ts,
        // 0042) and the real corpus — `spur feature refresh` (0058) relies on this.
        const featureContent = readFileSync(join(REPO_ROOT, 'config', 'templates', 'feature', 'default.md'), 'utf-8');
        expect(featureContent).toContain('## Tasks');
        expect(featureContent).toContain('<!-- AUTO-GENERATED by spur feature refresh -->');
        expect(featureContent).toContain('<!-- END AUTO-GENERATED -->');
    });

    test('init is idempotent — re-init does not overwrite templates without --force', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        // First init — templates are created.
        expect(await main(['init'], options)).toBe(0);
        const tmplPath = join(cwd, '.spur', 'tasks', 'templates', 'standard.md');
        expect(existsSync(tmplPath)).toBe(true);

        // Modify the template in-place to add a marker.
        const original = readFileSync(tmplPath, 'utf-8');
        const marker = '<!-- IDEMPOTENCE MARKER -->';
        writeFileSync(tmplPath, `${original}\n${marker}`, 'utf-8');

        // Re-init without --force is blocked (config.yaml already exists).
        expect(await main(['init'], options)).toBe(1);
        // Template still has our marker — not overwritten.
        const after = readFileSync(tmplPath, 'utf-8');
        expect(after).toContain(marker);

        // Re-init with --force does overwrite.
        expect(await main(['init', '--force'], options)).toBe(0);
        const forced = readFileSync(tmplPath, 'utf-8');
        expect(forced).not.toContain(marker);
    });

    test('section-matrix.yaml is copied to .spur/tasks/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const matrixPath = join(cwd, '.spur', 'tasks', 'section-matrix.yaml');
        expect(existsSync(matrixPath)).toBe(true);
        const content = readFileSync(matrixPath, 'utf-8');
        expect(content).toContain('variants:');
    });

    test('workflow lifecycle and pipeline YAMLs are copied to .spur/workflows/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const wfDir = join(cwd, '.spur', 'workflows');
        expect(existsSync(join(wfDir, 'task-lifecycle.yaml'))).toBe(true);
        expect(existsSync(join(wfDir, 'feature-lifecycle.yaml'))).toBe(true);
        expect(existsSync(join(wfDir, 'task-pipeline.yaml'))).toBe(true);
        expect(existsSync(join(wfDir, 'planning-pipeline.yaml'))).toBe(true);
    });

    test('docs scaffolds are copied to project-root docs/ (R1 — task 0088)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const docsDir = join(cwd, 'docs');
        expect(existsSync(join(docsDir, '99_PROJECT_CONSTITUTION.md'))).toBe(true);
        expect(existsSync(join(docsDir, '00_ADR.md'))).toBe(true);
        expect(existsSync(join(docsDir, '01_PRD.md'))).toBe(true);
        expect(existsSync(join(docsDir, '02_ROADMAP.md'))).toBe(true);
        expect(existsSync(join(docsDir, '03_ARCHITECTURE.md'))).toBe(true);
        expect(existsSync(join(docsDir, '04_DESIGN.md'))).toBe(true);
        expect(existsSync(join(docsDir, '05_FEATURES.md'))).toBe(true);
    });

    test('docs scaffolds are preserved even under --force (R1 — never clobber customized docs)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        // First init scaffolds the docs
        expect(await main(['init'], options)).toBe(0);

        // Customize one doc
        const prdPath = join(cwd, 'docs', '01_PRD.md');
        writeFileSync(prdPath, 'CUSTOM CONTENT — must survive re-init');

        // Re-init with --force must NOT overwrite the customized doc (preserve: true)
        expect(await main(['init', '--force'], options)).toBe(0);

        const content = readFileSync(prdPath, 'utf-8');
        expect(content).toBe('CUSTOM CONTENT — must survive re-init');
    });

    test('doc templates are also copied to .spur/templates/docs/', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const tmplDir = join(cwd, '.spur', 'templates', 'docs');
        expect(existsSync(join(tmplDir, '99_PROJECT_CONSTITUTION.md'))).toBe(true);
        expect(existsSync(join(tmplDir, '00_ADR.md'))).toBe(true);
        expect(existsSync(join(tmplDir, '05_FEATURES.md'))).toBe(true);
    });

    test('AGENTS.md scaffold is copied to project root with indexed-context block (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const agentsPath = join(cwd, 'AGENTS.md');
        expect(existsSync(agentsPath)).toBe(true);
        const content = readFileSync(agentsPath, 'utf-8');
        expect(content).toContain('.spur/context/');
        expect(content).toContain('indexed-context');
    });

    test('AGENTS.md substitutes {project-name} from --name and leaves no brace tokens (task 0242)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init', '--name', 'MyApp'], options)).toBe(0);

        const content = readFileSync(join(cwd, 'AGENTS.md'), 'utf-8');
        expect(content).toContain('MyApp');
        expect(content).not.toContain('{project-name}');
        expect(content).not.toContain('{project-description}');
        // No residual kebab-case brace tokens after init (R2 locked decision).
        expect(content.match(/\{[a-z0-9-]+\}/g)).toBeNull();
        expect(content).toContain('## Indexed context');
        expect(content).toContain('## Harness-first contract');
        expect(content).toContain('### Harness tool routing');
        expect(content).toContain('**Platform fallback:**');
    });

    test('AGENTS.md is preserved under --force (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, 'CUSTOM AGENTS — must survive re-init');

        expect(await main(['init', '--force'], options)).toBe(0);
        // Custom content is preserved (preserve: true — manifest never overwrites)
        const afterForce = readFileSync(agentsPath, 'utf-8');
        expect(afterForce).toContain('CUSTOM AGENTS — must survive re-init');
        // Block injection still fires idempotently — appends the activation block
        expect(afterForce).toContain('## Indexed context');
    });

    test('.gitignore gets .spur/context/ entry on init (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        const gitignorePath = join(cwd, '.gitignore');
        expect(existsSync(gitignorePath)).toBe(true);
        const content = readFileSync(gitignorePath, 'utf-8');
        expect(content).toContain('.spur/context/');
    });

    test('.gitignore append is idempotent — re-init does not duplicate entry (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init'], options)).toBe(0);

        // Manually re-run the append by calling init again with --force
        expect(await main(['init', '--force'], options)).toBe(0);

        const content = readFileSync(join(cwd, '.gitignore'), 'utf-8');
        const matches = content.match(/\.spur\/context\//g) ?? [];
        expect(matches.length).toBe(1);
    });

    test('--minimal mode still appends .spur/context/ to .gitignore (task 0232)', async () => {
        const cwd = await createTempProject();
        const { options } = await isolatedOptions(cwd);

        expect(await main(['init', '--minimal'], options)).toBe(0);

        const content = readFileSync(join(cwd, '.gitignore'), 'utf-8');
        expect(content).toContain('.spur/context/');
    });

    test('existing AGENTS.md without indexed-context block gets block appended (task 0232)', async () => {
        const cwd = await createTempProject();
        // Pre-create AGENTS.md with custom content (no indexed-context block)
        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, '# My Project\n\nCustom content here.\n', 'utf-8');

        const { options } = await isolatedOptions(cwd);
        expect(await main(['init'], options)).toBe(0);

        const content = readFileSync(agentsPath, 'utf-8');
        // Original content preserved
        expect(content).toContain('# My Project');
        expect(content).toContain('Custom content here.');
        // Block appended
        expect(content).toContain('## Indexed context');
        expect(content).toContain('.spur/context/anatomy.md');
    });

    test('existing AGENTS.md with indexed-context block is not duplicated (task 0232)', async () => {
        const cwd = await createTempProject();
        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, '# My Project\n\n## Indexed context\n\nAlready has it.\n', 'utf-8');

        const { options } = await isolatedOptions(cwd);
        expect(await main(['init'], options)).toBe(0);

        const content = readFileSync(agentsPath, 'utf-8');
        const markerCount = (content.match(/## Indexed context/g) ?? []).length;
        expect(markerCount).toBe(1);
        expect(content).toContain('Already has it.');
    });

    test('--minimal mode still injects block into existing AGENTS.md (task 0232)', async () => {
        const cwd = await createTempProject();
        const agentsPath = join(cwd, 'AGENTS.md');
        writeFileSync(agentsPath, '# Minimal Project\n', 'utf-8');

        const { options } = await isolatedOptions(cwd);
        expect(await main(['init', '--minimal'], options)).toBe(0);

        const content = readFileSync(agentsPath, 'utf-8');
        expect(content).toContain('## Indexed context');
    });
});
