import { describe, expect, test } from 'bun:test';
import { MarkdownDocument } from '@gobing-ai/spur-domain';

// ---------------------------------------------------------------------------
// Fixture: representative task file (design §2.1 — `##` title, `###` sections)
// ---------------------------------------------------------------------------

const TASK_FILE = [
    '---',
    'name: Implement X',
    'status: wip',
    'created_at: 2026-06-13T00:00:00.000Z',
    'tags: ["api","refactor"]',
    '---',
    '',
    '## 0050. Implement X',
    '',
    '### Background',
    '',
    'Some background text.',
    'Multiple lines.',
    '',
    '### Requirements',
    '',
    '- R1: Do the thing',
    '- R2: Do it well',
    '',
    '### Solution',
    '',
    'Code goes here.',
    '',
    '### References',
    '',
    '',
].join('\n');

// A task file with no frontmatter (edge case).
const TASK_NO_FM = ['## 0051. No frontmatter task', '', '### Background', '', 'Just body text.', ''].join('\n');

// A task file with malformed YAML (frontmatter exists but doesn't parse).
const TASK_BAD_YAML = [
    '---',
    'name: Bad',
    'status: [unclosed',
    '---',
    '',
    '## 0052. Bad YAML',
    '',
    '### Background',
    '',
    'Body.',
    '',
].join('\n');

// ---------------------------------------------------------------------------
// Fixture: representative feature file (design §2.2 — `#` title, `##` sections)
// ---------------------------------------------------------------------------

const FEATURE_FILE = [
    '---',
    'schema_version: 1',
    'id: F1',
    'name: Planning foundation',
    'status: active',
    'priority: P0',
    '---',
    '',
    '# F1: Planning foundation',
    '',
    '## Goal',
    '',
    'The W0 substrate.',
    '',
    '## Tasks',
    '',
    '<!-- AUTO-GENERATED by spur feature refresh -->',
    '| WBS | Task | Status |',
    '|-----|------|--------|',
    '| 0042 | MarkdownDocument | backlog |',
    '<!-- END AUTO-GENERATED -->',
    '',
    '## Notes',
    '',
    'Some notes.',
    '',
    '## History',
    '',
    '- 2026-06-12 — created',
    '',
].join('\n');

// ---------------------------------------------------------------------------
// MarkdownDocument.parse() + serialize()
// ---------------------------------------------------------------------------

describe('MarkdownDocument', () => {
    describe('parse() frontmatter', () => {
        test('parses valid YAML frontmatter into data object', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.frontmatter).not.toBeNull();
            expect(doc.frontmatterData).toEqual({
                name: 'Implement X',
                status: 'wip',
                created_at: '2026-06-13T00:00:00.000Z',
                tags: ['api', 'refactor'],
            });
        });

        test('preserves raw frontmatter text for re-serialization', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.frontmatterRaw).toContain('name: Implement X');
            expect(doc.frontmatterRaw).toContain('tags: ["api","refactor"]');
        });

        test('returns null frontmatter when file has no frontmatter block', () => {
            const doc = MarkdownDocument.parse(TASK_NO_FM, 'task');
            expect(doc.frontmatter).toBeNull();
            expect(doc.frontmatterRaw).toBeNull();
            expect(doc.frontmatterData).toBeNull();
        });

        test('falls back to empty object on malformed YAML without throwing', () => {
            const doc = MarkdownDocument.parse(TASK_BAD_YAML, 'task');
            expect(doc.frontmatter).not.toBeNull();
            expect(doc.frontmatterData).toEqual({});
            // Raw text is still available for lossless round-trip.
            expect(doc.frontmatterRaw).toContain('status: [unclosed');
        });
    });

    // -----------------------------------------------------------------------
    // Lossless round-trip (R1 — core contract)
    // -----------------------------------------------------------------------

    describe('lossless round-trip', () => {
        test('task file round-trips byte-identically when no modifications are made', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.serialize()).toBe(TASK_FILE);
        });

        test('feature file round-trips byte-identically when no modifications are made', () => {
            const doc = MarkdownDocument.parse(FEATURE_FILE, 'feature');
            expect(doc.serialize()).toBe(FEATURE_FILE);
        });

        test('no-frontmatter file round-trips byte-identically', () => {
            const doc = MarkdownDocument.parse(TASK_NO_FM, 'task');
            expect(doc.serialize()).toBe(TASK_NO_FM);
        });

        test('malformed-YAML file round-trips byte-identically (raw text preserved)', () => {
            const doc = MarkdownDocument.parse(TASK_BAD_YAML, 'task');
            expect(doc.serialize()).toBe(TASK_BAD_YAML);
        });
    });

    // -----------------------------------------------------------------------
    // getSection()
    // -----------------------------------------------------------------------

    describe('getSection()', () => {
        test('returns body text for an existing section', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            const bg = doc.getSection('Background');
            expect(bg).toContain('Some background text.');
            expect(bg).toContain('Multiple lines.');
        });

        test('returns body that starts after the heading line', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            const sol = doc.getSection('Solution');
            expect(sol).not.toContain('### Solution');
            expect(sol).toContain('Code goes here.');
        });

        test('returns null for a canonical section absent from the file', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.getSection('Testing')).toBeNull();
        });

        test('throws on unknown (non-canonical) section name', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(() => doc.getSection('Random')).toThrow('Unknown section "Random"');
        });

        test('feature domain recognizes feature canonical sections', () => {
            const doc = MarkdownDocument.parse(FEATURE_FILE, 'feature');
            expect(doc.getSection('Goal')).toContain('The W0 substrate.');
            expect(doc.getSection('Notes')).toContain('Some notes.');
        });

        test('feature domain rejects task-only section names', () => {
            const doc = MarkdownDocument.parse(FEATURE_FILE, 'feature');
            expect(() => doc.getSection('Requirements')).toThrow('Unknown section');
        });
    });

    // -----------------------------------------------------------------------
    // replaceSection() (R2 — section get/replace by canonical name)
    // -----------------------------------------------------------------------

    describe('replaceSection()', () => {
        test('replaces section body and reflect in serialize()', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            doc.replaceSection('Background', 'New background content.');
            const out = doc.serialize();
            expect(out).toContain('New background content.');
            expect(out).not.toContain('Some background text.');
            // Heading is preserved.
            expect(out).toContain('### Background');
        });

        test('only the target section changes — other sections are untouched', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            doc.replaceSection('Background', 'Replaced.');
            const out = doc.serialize();
            // Solution section untouched.
            expect(out).toContain('Code goes here.');
            // Requirements section untouched.
            expect(out).toContain('- R1: Do the thing');
        });

        test('throws on unknown section name', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(() => doc.replaceSection('Random', 'x')).toThrow('Unknown section');
        });

        test('upserts a canonical section absent from the file, in canonical order', () => {
            // WHY: the progressive-section lifecycle adds sections as a task moves
            // through statuses; writing an absent canonical section inserts it
            // rather than failing, so an agent can fill e.g. Solution at wip.
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.hasSection('Testing')).toBe(false);
            doc.replaceSection('Testing', 'All green.');
            const out = doc.serialize();
            expect(out).toContain('### Testing');
            expect(out).toContain('All green.');
            // Inserted in canonical order: Testing comes after Solution, before Review.
            const order = ['Solution', 'Testing', 'Review'].map((s) => out.indexOf(`### ${s}`));
            const present = order.filter((i) => i >= 0);
            expect(present).toEqual([...present].sort((a, b) => a - b));
            // Existing content preserved.
            expect(out).toContain('Code goes here.');
        });
    });

    // -----------------------------------------------------------------------
    // replaceMarkerRegion() (R3 — auto-gen marker region)
    // -----------------------------------------------------------------------

    describe('replaceMarkerRegion()', () => {
        test('replaces marker region content while preserving surrounding text', () => {
            const doc = MarkdownDocument.parse(FEATURE_FILE, 'feature');
            const newTable = '| WBS | Task | Status |\n|-----|------|--------|\n| 0099 | New | done |';
            doc.replaceMarkerRegion('Tasks', newTable);

            const out = doc.serialize();
            expect(out).toContain('| 0099 | New | done |');
            expect(out).not.toContain('| 0042 | MarkdownDocument |');
            // Markers are present.
            expect(out).toContain('<!-- AUTO-GENERATED');
            expect(out).toContain('<!-- END AUTO-GENERATED');
        });

        test('text outside the markers is byte-preserved', () => {
            const doc = MarkdownDocument.parse(FEATURE_FILE, 'feature');
            const originalGoal = doc.getSection('Goal');
            doc.replaceMarkerRegion('Tasks', 'replaced');
            const out = doc.serialize();
            // Goal section text should still be intact.
            expect(out).toContain('The W0 substrate.');
            void originalGoal;
        });

        test('throws when section has no marker region', () => {
            const doc = MarkdownDocument.parse(FEATURE_FILE, 'feature');
            expect(() => doc.replaceMarkerRegion('Goal', 'x')).toThrow('No marker region');
        });

        test('throws on unknown section name', () => {
            const doc = MarkdownDocument.parse(FEATURE_FILE, 'feature');
            expect(() => doc.replaceMarkerRegion('Random', 'x')).toThrow('Unknown section');
        });
    });

    // -----------------------------------------------------------------------
    // hasSection() + sectionNames
    // -----------------------------------------------------------------------

    describe('hasSection() and sectionNames', () => {
        test('hasSection returns true for present sections', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.hasSection('Background')).toBe(true);
            expect(doc.hasSection('Solution')).toBe(true);
        });

        test('hasSection returns false for absent sections', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.hasSection('Testing')).toBe(false);
        });

        test('sectionNames lists all sections in order', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.sectionNames).toEqual(['Background', 'Requirements', 'Solution', 'References']);
        });

        test('sectionNames is empty for a file with no sections at the heading level', () => {
            const bodyOnly = '---\nstatus: wip\n---\n\nJust some text, no headings.\n';
            const doc = MarkdownDocument.parse(bodyOnly, 'task');
            expect(doc.sectionNames).toEqual([]);
        });
    });

    // -----------------------------------------------------------------------
    // Heading convention isolation (R2 — both conventions via domain param)
    // -----------------------------------------------------------------------

    describe('heading level isolation', () => {
        test('task domain (level 3) ignores level-2 headings inside code blocks', () => {
            const content = [
                '## 0050. Title',
                '',
                '### Background',
                '',
                '```markdown',
                '## This looks like a section but is in a code block',
                '### This too',
                '```',
                '',
                '### Solution',
                '',
                'Real solution.',
                '',
            ].join('\n');
            const doc = MarkdownDocument.parse(content, 'task');
            // Only Background and Solution should be found.
            expect(doc.sectionNames).toEqual(['Background', 'Solution']);
        });

        test('feature domain (level 2) does not pick up level-3 headings', () => {
            const content = [
                '# F1: Title',
                '',
                '## Goal',
                '',
                'Goal text.',
                '',
                '### This is h3, should not be a section',
                '',
                'Still part of Goal.',
                '',
            ].join('\n');
            const doc = MarkdownDocument.parse(content, 'feature');
            expect(doc.sectionNames).toEqual(['Goal']);
            expect(doc.getSection('Goal')).toContain('### This is h3');
        });
    });

    // -----------------------------------------------------------------------
    // Edge cases
    // -----------------------------------------------------------------------

    describe('edge cases', () => {
        test('empty string round-trips', () => {
            const doc = MarkdownDocument.parse('', 'task');
            expect(doc.serialize()).toBe('');
            expect(doc.sectionNames).toEqual([]);
        });

        test('file with frontmatter but no body sections round-trips', () => {
            const content = '---\nstatus: wip\n---\n\nJust a paragraph.\n';
            const doc = MarkdownDocument.parse(content, 'task');
            expect(doc.serialize()).toBe(content);
            expect(doc.sectionNames).toEqual([]);
        });

        test('frontmatter with non-object YAML (scalar) falls back to empty object', () => {
            const content = '---\njustastring\n---\n\n## 0050. Title\n\n### Background\n\nBody.\n';
            const doc = MarkdownDocument.parse(content, 'task');
            expect(doc.frontmatterData).toEqual({});
        });

        test('frontmatter with array YAML falls back to empty object', () => {
            const content = '---\n- item1\n- item2\n---\n\n## 0050. Title\n\n### Background\n\nBody.\n';
            const doc = MarkdownDocument.parse(content, 'task');
            expect(doc.frontmatterData).toEqual({});
        });

        test('CRLF line endings are handled in frontmatter detection', () => {
            const content = '---\r\nstatus: wip\r\n---\r\n\r\n## 0050. Title\r\n\r\n### Background\r\n\r\nBody.\r\n';
            const doc = MarkdownDocument.parse(content, 'task');
            expect(doc.frontmatterData).toEqual({ status: 'wip' });
            expect(doc.hasSection('Background')).toBe(true);
        });

        test('domain getter returns the domain kind', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            expect(doc.domain).toBe('task');
        });
    });

    // -----------------------------------------------------------------------
    // setFrontmatterField() (R4 — replaces regex frontmatter read-modify-write)
    // -----------------------------------------------------------------------

    describe('setFrontmatterField()', () => {
        test('appends a new field, preserving existing fields and body', () => {
            const content = '---\nname: "Demo"\nstatus: wip\n---\n\n## 0042. Body\n';
            const doc = MarkdownDocument.parse(content, 'task');
            doc.setFrontmatterField('assignee', 'planner');
            const out = doc.serialize();
            expect(out).toContain('assignee: planner');
            expect(out).toContain('name: "Demo"');
            expect(out).toContain('status: wip');
            expect(out).toContain('## 0042. Body');
            // Output remains a valid re-parseable document.
            expect(MarkdownDocument.parse(out, 'task').frontmatterData).toMatchObject({ assignee: 'planner' });
        });

        test('replaces an existing field in place', () => {
            const content = '---\nname: "Demo"\nassignee: oldagent\n---\n\nbody\n';
            const doc = MarkdownDocument.parse(content, 'task');
            doc.setFrontmatterField('assignee', 'newagent');
            const out = doc.serialize();
            expect(out).toContain('assignee: newagent');
            expect(out).not.toContain('oldagent');
        });

        test('prepends a frontmatter block when the file has none', () => {
            const content = '## 0042. No frontmatter\n\nbody\n';
            const doc = MarkdownDocument.parse(content, 'task');
            doc.setFrontmatterField('assignee', 'planner');
            const out = doc.serialize();
            expect(out.startsWith('---\nassignee: planner\n---\n\n')).toBe(true);
            expect(out).toContain('## 0042. No frontmatter');
        });

        test('writes $-sequences in existing values verbatim', () => {
            const content = '---\nname: "Cost $1.00 and $& literal"\nstatus: wip\n---\n\nbody\n';
            const doc = MarkdownDocument.parse(content, 'task');
            doc.setFrontmatterField('assignee', 'planner');
            const out = doc.serialize();
            expect(out).toContain('name: "Cost $1.00 and $& literal"');
            expect(out).toContain('assignee: planner');
        });

        test('leaves the body byte-identical when only frontmatter changes', () => {
            const doc = MarkdownDocument.parse(TASK_FILE, 'task');
            const bodyBefore = TASK_FILE.slice(TASK_FILE.indexOf('## 0050.'));
            doc.setFrontmatterField('assignee', 'planner');
            const out = doc.serialize();
            expect(out.slice(out.indexOf('## 0050.'))).toBe(bodyBefore);
        });
    });
});
