import { describe, expect, test } from 'bun:test';
import type { HistoryArtifact } from '../../src/analytics/artifact';
import { HISTORY_ARTIFACT_SCHEMA_VERSION } from '../../src/analytics/artifact';
import { formatSummary } from '../../src/analytics/costs';
import type { DerivedVariables } from '../../src/analytics/derived';
import { renderForensics } from '../../src/analytics/render-forensics';
import { artifactToSummary, renderReport } from '../../src/analytics/render-report';
import {
    REPORT_MODES,
    renderMarkdown,
    resolveReportMode,
    UnknownReportModeError,
} from '../../src/analytics/report-modes';

function emptyTokens() {
    return {
        inputTokens: 0,
        outputTokens: 0,
        cacheReadTokens: 0,
        cacheWriteTokens: 0,
        costUsd: 0,
        records: 0,
        recordsWithUsage: 0,
        messages: 0,
        toolCalls: 0,
        durationMs: 0,
        durationUnmeasured: 0,
        assistantDurationMs: 0,
        assistantDurationUnmeasured: 0,
    };
}

function derived(): DerivedVariables {
    return {
        phases: {
            phaseSupport: 'supported',
            phases: [
                { name: 'recon', startedAt: '2026-08-13T10:00:00Z', endedAt: '2026-08-13T10:02:30Z', source: 'todo' },
                {
                    name: 'implement',
                    startedAt: '2026-08-13T10:02:30Z',
                    endedAt: '2026-08-13T10:10:00Z',
                    source: 'todo',
                },
            ],
        },
        timeDecomposition: {
            llmMs: 120_000,
            toolMs: 180_000,
            idleMs: 60_000,
            unattributedMs: 30_000,
            spanMs: 390_000,
            spanExcludedSessions: 0,
        },
        bottlenecks: [{ label: 'LLM latency', ms: 120_000, share: 0.31 }],
    };
}

function artifact(overrides: Partial<HistoryArtifact> = {}): HistoryArtifact {
    return {
        schemaVersion: HISTORY_ARTIFACT_SCHEMA_VERSION,
        generatedAt: '2026-08-07T00:00:00Z',
        spurVersion: '1.0.0',
        selector: { since: null, until: null, sources: null, sessionId: null, runId: null, taskWbs: null },
        coverage: [],
        totals: {
            ...emptyTokens(),
            inputTokens: 1_000_000,
            outputTokens: 500_000,
            cacheReadTokens: 400_000,
            cacheWriteTokens: 100_000,
            records: 10,
            recordsWithUsage: 8,
            messages: 40,
            toolCalls: 25,
        },
        bySource: { claude: { ...emptyTokens(), records: 10 } },
        byModel: { 'claude-3': { ...emptyTokens(), records: 10 } },
        daily: [],
        byTool: [
            {
                toolName: 'Read',
                calls: 10,
                errors: 1,
                durationMsTotal: 5000,
                durationMsMean: 500,
                durationMsMax: 1200,
                durationUnmeasured: 0,
                resultBytes: 2048,
            },
        ],
        bySession: [],
        loops: [],
        warnings: [],
        derived: derived(),
        ...overrides,
    };
}

describe('report mode registry (R1)', () => {
    test('resolves default and forensics', () => {
        expect(REPORT_MODES.default).toBe(renderReport);
        expect(resolveReportMode('default')).toBe(renderReport);
        expect(resolveReportMode('forensics')).toBe(renderForensics);
    });

    test('default mode reproduces the legacy report output byte-for-byte', () => {
        const a = artifact();
        expect(resolveReportMode('default')(a)).toBe(renderReport(a));
    });

    test('unknown mode fails naming the registered modes', () => {
        try {
            resolveReportMode('spend');
            expect.unreachable('resolveReportMode must throw');
        } catch (e) {
            expect(e).toBeInstanceOf(UnknownReportModeError);
            const msg = (e as Error).message;
            expect(msg).toContain("'spend'");
            expect(msg).toContain('default');
            expect(msg).toContain('forensics');
        }
    });
});

describe('renderMarkdown is mode-aware (R1/R8)', () => {
    test('default mode reproduces the legacy sidecar format', () => {
        const a = artifact();
        const md = renderMarkdown(a);
        expect(md).toContain('<!-- Generated by spur history report');
        expect(md).toContain(formatSummary(artifactToSummary(a)));
    });

    test('forensics mode wraps the forensics body', () => {
        const md = renderMarkdown(artifact(), 'forensics');
        expect(md).toContain('<!-- Generated by spur history report');
        expect(md).toContain('## Session Data Summary');
        expect(md).toContain('```');
    });
});
