/**
 * Generate the plugin-side copy of the domain artifact-digest authority (task 0669).
 *
 * `packages/domain/src/analytics/artifact-digest.ts` owns the semantic digest, but the plugin
 * script `plugins/sp/scripts/history-anatomy-cache.ts` is an ADR-065 standard script: its committed
 * `.mjs` twin must run under bare `node` with no monorepo dependency, and `superskill script
 * convert` cannot bundle a `@gobing-ai/spur-domain` import. The bridge is a **generated** ESM
 * bundle under `plugins/sp/lib/`, committed, imported by the script through a relative path —
 * which the twin generator inlines successfully (proven in task 0669 Q&A probes).
 *
 * Outputs (both gitignored from Biome, both committed):
 *   plugins/sp/lib/artifact-digest.generated.mjs    — standalone ESM bundle of the authority
 *   plugins/sp/lib/artifact-digest.generated.d.mts  — declarations for the surface the script uses
 *
 * `bundleIdeaHandoffLib` (task 0824) applies the same bridge to the idea-pipeline handoff
 * writer: `packages/app/src/workflow/idea-handoff-cli.ts` is bundled (minified, with
 * `import.meta.main` pinned to false) into `plugins/sp/lib/idea-handoff.generated.mjs` so the
 * registered standard twin `plugins/sp/scripts/idea-handoff.mjs` runs under bare `node` in
 * seeded projects with no monorepo checkout.
 *
 * Run via `bun run build:plugin-lib`; chained ahead of `build:scripts`.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const REPO_ROOT = new URL('../../', import.meta.url).pathname;
const ENTRY = join(REPO_ROOT, 'packages/domain/src/analytics/artifact-digest.ts');
const OUT_DIR = join(REPO_ROOT, 'plugins/sp/lib');

// ponytail: the .d.mts carries the fixed signatures the script consumes; widen here (not by hand
// in the lib file) if the script ever imports more of the authority.
const DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/domain/src/analytics/artifact-digest.ts (task 0669).
 */
export declare const ARTIFACT_ARRAY_CLASSIFICATION: Readonly<Record<string, 'ranked' | 'set'>>;
export declare const RANKED_ARTIFACT_KEYS: ReadonlySet<string>;
export declare function semanticArtifactDigest(artifactJson: unknown): string;
`;

export async function bundlePluginLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [ENTRY],
        target: 'node',
        format: 'esm',
        minify: false,
        root: join(REPO_ROOT, 'packages/domain/src/analytics'),
        naming: 'artifact-digest.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`plugin-lib bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'artifact-digest.generated.mjs');
    const dmts = join(outDir, 'artifact-digest.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, DECLS);
    return { mjs, dmts };
}

// ponytail: the .d.mts carries the signatures the workflow handoff consumes; the plugin twin
// only invokes the module, so the env/outcome shapes stay loose on purpose.
const IDEA_HANDOFF_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/workflow/idea-handoff-cli.ts (task 0824).
 */
export declare interface IdeaHandoffCliEnv {
    __runId?: string;
    featureId?: string;
    spurBin?: string;
}
export declare interface IdeaHandoffCliOutcome {
    exitCode: number;
    result?: unknown;
}
export declare function runIdeaHandoffCli(
    env: IdeaHandoffCliEnv,
    run?: (input: { runId: string; featureId: string; spurBin: string }) => Promise<unknown>,
): Promise<IdeaHandoffCliOutcome>;
`;

/**
 * Bundle the idea handoff CLI (task 0824) into a standalone node-runnable ESM module.
 * Minified; `import.meta.main` is pinned to `false` so importing the bundle never triggers
 * the entrypoint block — the plugin twin calls `runIdeaHandoffCli` itself.
 */
export async function bundleIdeaHandoffLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/workflow/idea-handoff-cli.ts')],
        target: 'node',
        format: 'esm',
        minify: { whitespace: true, syntax: true, identifiers: false },
        define: { 'import.meta.main': 'false' },
        root: join(REPO_ROOT, 'packages/app/src/workflow'),
        naming: 'idea-handoff.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`idea handoff bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'idea-handoff.generated.mjs');
    const dmts = join(outDir, 'idea-handoff.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, IDEA_HANDOFF_DECLS);
    return { mjs, dmts };
}

/** Bundle only the inline driver's existing application operations and schema assets. */
export async function bundleInlineRunLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    // Keep the temporary entry inside the repo so workspace dependencies resolve consistently.
    // ponytail: fixed scratch path — the mkdtemp suffix leaked into Bun's minified
    // identifier assignment and broke the determinism gate; builds are serialized.
    const scratch = join(REPO_ROOT, '.inline-run-bundle');
    try {
        mkdirSync(scratch, { recursive: true });
        const entry = join(scratch, 'entry.ts');
        writeFileSync(
            entry,
            [
                "export { createOrAttachInlineRun, openInlineRunProjectDb } from '../packages/app/src/services/inline-run-setup';",
                "export { computeProofInputFingerprint, readProofInputContents } from '../packages/app/src/workflow/proof-input-fingerprint';",
                "export { createWorkflowActionTraceWriter } from '../packages/app/src/workflow/action-trace';",
                "export { splitLaunchCommand } from '../packages/app/src/workflow/split-launch-command';",
                // Feature verification receipt (D63 task 0915): the standard script
                // records/validates receipts and resolves the selected verifier
                // definition through the same seams in both layouts.
                "export { captureFeatureReceiptDigest, completeFeatureVerificationReceipt, DEFAULT_FEATURE_VERIFICATION_CMD, featureReceiptPaths, startFeatureVerificationReceipt, validateFeatureVerificationReceipt } from '../packages/app/src/workflow/feature-verification-receipt';",
                "export { resolveWorkflowDefinition } from '../packages/app/src/workflow/workflow-resolver';",
                "export { ArtifactDao, RunDao } from '../packages/domain/src/dao';",
                "export { EMBEDDED_SPUR_SCHEMAS } from '../apps/cli/src/config/embedded-schemas';",
            ].join('\n'),
        );
        const result = await Bun.build({
            entrypoints: [entry],
            target: 'node',
            format: 'esm',
            minify: { whitespace: true, syntax: true, identifiers: false },
            external: ['bun:sqlite'],
            define: { 'import.meta.main': 'false' },
            naming: 'inline-run.generated.mjs',
            outdir: outDir,
        });
        if (!result.success) {
            throw new Error(`inline run bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
        }
        const mjs = join(outDir, 'inline-run.generated.mjs');
        const dmts = join(outDir, 'inline-run.generated.d.mts');
        writeFileSync(
            dmts,
            [
                '/** GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit. Requires Bun for SQLite. */',
                ...[
                    'createOrAttachInlineRun',
                    'openInlineRunProjectDb',
                    'computeProofInputFingerprint',
                    'readProofInputContents',
                    'createWorkflowActionTraceWriter',
                ].map((name) => `export declare const ${name}: typeof import('@gobing-ai/spur-app').${name};`),
                ...[
                    'captureFeatureReceiptDigest',
                    'completeFeatureVerificationReceipt',
                    'DEFAULT_FEATURE_VERIFICATION_CMD',
                    'featureReceiptPaths',
                    'startFeatureVerificationReceipt',
                    'validateFeatureVerificationReceipt',
                    'resolveWorkflowDefinition',
                ].map((name) => `export declare const ${name}: typeof import('@gobing-ai/spur-app').${name};`),
                ...['ArtifactDao', 'RunDao'].map(
                    (name) => `export declare const ${name}: typeof import('@gobing-ai/spur-domain').${name};`,
                ),
                'export declare const EMBEDDED_SPUR_SCHEMAS: ReadonlyMap<string, string>;',
                'export declare function splitLaunchCommand(value: string, label: string): { command: string; leadingArgs: string[] } | { error: string };',
                '',
            ].join('\n'),
        );
        return { mjs, dmts };
    } finally {
        rmSync(scratch, { recursive: true, force: true });
    }
}

if (import.meta.main) {
    const { mjs, dmts } = await bundlePluginLib();
    console.log(`plugin-lib generated: ${mjs}, ${dmts}`);
    const handoff = await bundleIdeaHandoffLib();
    console.log(`idea-handoff lib generated: ${handoff.mjs}, ${handoff.dmts}`);
    const inlineRun = await bundleInlineRunLib();
    console.log(`inline-run lib generated: ${inlineRun.mjs}, ${inlineRun.dmts}`);
}
