/**
 * Generate the plugin-side lib bundles for thin plugin scripts (ADR-130 lib rule, task 1005).
 *
 * `packages/app` owns the workflow/history logic cores, but the plugin scripts
 * `plugins/sp/scripts/workflow-step-profile.ts` and `history-anatomy-cache.ts` are ADR-065
 * standard scripts: their committed `.mjs` twins must run under bare `node` with no monorepo
 * dependency, and `superskill script convert` cannot bundle workspace imports. The bridge is a
 * **generated** ESM bundle under `plugins/sp/lib/`, committed, imported and re-exported by the
 * script through a relative path.
 *
 * Outputs (gitignored from Biome, all committed):
 *   plugins/sp/lib/step-profile.generated.mjs|.d.mts     — step-profile core (task 1005 R1)
 *   plugins/sp/lib/history-anatomy.generated.mjs|.d.mts  — history-anatomy cache core (task 1005 R2)
 *   plugins/sp/lib/idea-handoff.generated.mjs|.d.mts     — minified CLI wrapper (task 0824)
 *   plugins/sp/lib/inline-run.generated.mjs|.d.mts       — inline driver surface (task 0972)
 *   plugins/sp/lib/residual-scan.generated.mjs|.d.mts    — residual-scan core (task 1003 R5)
 *   plugins/sp/lib/quality-gate.generated.mjs|.d.mts     — quality-gate core (task 1006 R1)
 *
 * `bundleIdeaHandoffLib` (task 0824) minifies with `import.meta.main` pinned to `false`; the
 * unminified lib bundles stay byte-deterministic via `normalizeBundleComments` (task 1003 R5
 * gate). Run via `bun run build:plugin-lib`; chained ahead of `build:scripts`.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));

/**
 * Bun.build emits entrypoint comments relative to process.cwd(), so the committed bytes of an
 * unminified lib differed between a root-cwd generation (`// packages/...`) and a
 * scripts-workspace regeneration (`// ../packages/...`). Pin to repo-relative for
 * cwd-independent determinism (task 1003 R5 gate).
 */
function normalizeBundleComments(mjsPath: string): void {
    const raw = readFileSync(mjsPath, 'utf8');
    const normalized = raw.replace(/^\/\/ (?:\.\.\/)+/gm, '// ');
    if (normalized !== raw) writeFileSync(mjsPath, normalized);
}

const OUT_DIR = join(REPO_ROOT, 'plugins/sp/lib');

// ponytail: the .d.mts mirrors each app module's full export surface; widen here (not by hand
// in the lib files) if the scripts ever import more.
const STEP_PROFILE_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/workflow/step-profile.ts (task 1005 R1).
 */
export declare interface ActionCostLike {
    cacheHit: number | null;
}
export declare interface ActionCostAttributionLike {
    exact: ActionCostLike | null;
    estimated: ActionCostLike | null;
}
export declare interface TraceActionEvent {
    kind: string;
    node?: string;
    actionKind?: string;
    durationMs?: number | null;
    startedAt?: string | null;
    completedAt?: string | null;
    invocation?: Record<string, string | number | boolean> | null;
    cost?: ActionCostAttributionLike | null;
}
export declare interface StepProfileRun {
    runId: string;
    events: readonly TraceActionEvent[];
}
export declare interface TraceRunEntry {
    runId: string;
    isDryRun?: boolean;
    status?: string;
    workflowName?: string;
}
export declare type SessionMode = 'fresh' | 'resumed' | 'mixed';
export declare interface StepProfileExecution {
    runId: string;
    node: string;
    actionKind: string;
    durationMs: number | null;
    idleGapMs: number | null;
    session: 'fresh' | 'resumed' | null;
    cacheHit: number | null;
}
export declare interface StepProfileRow {
    node: string;
    actionKind: string;
    runs: number;
    executions: number;
    durationMs: { p50: number | null; max: number | null };
    idleGapMs: { p50: number | null };
    session: SessionMode | null;
    cacheHit: { p50: number | null; known: number; of: number };
    flags: string[];
}
export declare interface StepProfile {
    workflow: string;
    windowSec: number;
    sampledRuns: number;
    rows: StepProfileRow[];
}
export declare const DEFAULT_LAST: number;
export declare const DEFAULT_WINDOW_SEC: number;
export declare function nearestRankP50(values: readonly number[]): number | null;
export declare function extractExecutions(runId: string, events: readonly TraceActionEvent[]): StepProfileExecution[];
export declare function rowFlags(row: StepProfileRow, windowSec: number): string[];
export declare function buildRows(executions: readonly StepProfileExecution[], windowSec: number): StepProfileRow[];
export declare function buildStepProfile(input: {
    workflow: string;
    windowSec: number;
    runs: readonly StepProfileRun[];
}): StepProfile;
export declare function nonDryRuns(entries: readonly TraceRunEntry[]): TraceRunEntry[];
export declare function formatStepProfileHuman(profile: StepProfile): string;
`;

/**
 * Bundle the step-profile aggregation core (task 1005 R1) into a standalone node-runnable ESM
 * module. Unminified — the source is pure (node builtins only), so determinism holds. The plugin
 * script `plugins/sp/scripts/workflow-step-profile.ts` keeps the IO glue and re-exports this.
 */
export async function bundleStepProfileLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/workflow/step-profile.ts')],
        target: 'node',
        format: 'esm',
        minify: false,
        root: join(REPO_ROOT, 'packages/app/src/workflow'),
        naming: 'step-profile.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`step-profile bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'step-profile.generated.mjs');
    const dmts = join(outDir, 'step-profile.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, STEP_PROFILE_DECLS);
    normalizeBundleComments(mjs);
    return { mjs, dmts };
}

const HISTORY_ANATOMY_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/services/history-anatomy.ts (task 1005 R2).
 */
export declare interface CacheIdentity {
    contractVersion: string;
    mode: 'daily' | 'ad-hoc';
    date: string;
    timezone: string;
    bounds: { since: string; until: string };
    sources: string[];
}
export declare interface CacheProvenance {
    identity: CacheIdentity;
    windowState: 'provisional' | 'closed';
    generatedAt: string;
    validatedAt: string;
    artifactDigest: string;
    baselineArtifactDigest: string | null;
    contractDigest: string;
    skillDigest: string;
    workflowDigest: string;
    helperDigest: string;
    coverage: Array<{ source: string; status: string; lastImportedAt: string | null }>;
    runId?: string;
    currentArtifactPath?: string;
    baselineArtifactPath?: string | null;
    spurVersion?: string;
    schemaVersion?: number;
    executor?: string;
    model?: string;
    cacheDisposition?: CacheDisposition;
}
export declare type CacheDisposition = 'hit' | 'miss' | 'forced-recompute';
export declare interface CacheDecision {
    disposition: CacheDisposition;
    reasons: string[];
}
export declare const REPORT_SECTIONS: string[];
export declare const FINDING_FIELDS: string[];
export declare function semanticArtifactDigest(artifactJson: unknown): string;
export declare function parseProvenance(reportMarkdown: string): CacheProvenance | null;
export declare function decideCache(
    cached: CacheProvenance | null,
    current: CacheProvenance,
    opts: { recompute: boolean; dayClosed: boolean },
): CacheDecision;
export declare function checkReportStructure(reportMarkdown: string): { ok: boolean; problems: string[] };
export declare function logicDigest(path: string | undefined): string;
export declare function importedSnapshotAsOf(coverage: CacheProvenance['coverage']): string;
export declare function resolvePaths(opts: {
    helper: string;
    reportDir: string;
    date?: string;
    output?: string;
    now?: Date;
    tz?: string;
    mode?: string;
    since?: string;
    until?: string;
}): string;
export declare type SelectorValidation =
    | {
          ok: true;
          mode: 'daily' | 'ad-hoc';
          date: string | null;
          focus: string | null;
          since: string | null;
          until: string | null;
      }
    | { ok: false; errors: string[] };
export declare function validateSelector(opts: {
    mode?: string;
    date?: string;
    since?: string;
    until?: string;
    focus?: string;
    recompute?: string;
    output?: string;
}): SelectorValidation;
export declare interface ProbeOptions {
    artifact: string;
    target: string;
    baseline?: string;
    mode: 'daily' | 'ad-hoc';
    date?: string;
    recompute: boolean;
    executor?: string;
    model?: string;
    skillDir?: string;
    contractFile?: string;
    workflowFile?: string;
    helperFile?: string;
    contractVersion?: string;
    runId?: string;
    spurVersion?: string;
    now?: Date;
}
export declare function buildProvenance(opts: ProbeOptions): CacheProvenance;
export declare function probe(opts: ProbeOptions): { decision: CacheDecision; current: CacheProvenance };
export declare function renderProvenanceFrontmatter(p: CacheProvenance): string;
export declare function bannerLine(p: CacheProvenance): string;
export declare function stampReport(candidateMarkdown: string, p: CacheProvenance): string;
export declare function refreshReport(publishedMarkdown: string, validatedAt: string, disposition: CacheDisposition): string;
export declare function publishAtomically(candidatePath: string, targetPath: string): void;
export declare interface CacheCliResult {
    exitCode: number;
    stdout: string;
    stderr: string;
}
export declare function porcelainPaths(text: string): Set<string>;
export declare function diffPorcelain(before: string, now: string, expects: Set<string>): string[];
`;

/**
 * Bundle the history-anatomy cache core (task 1005 R2) into a standalone node-runnable ESM
 * module. Unminified — the source is pure (node builtins plus the domain artifact digest, which
 * Bun.build inlines), so determinism holds. The plugin script
 * `plugins/sp/scripts/history-anatomy-cache.ts` keeps the CLI glue and re-exports this.
 */
export async function bundleHistoryAnatomyLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/services/history-anatomy.ts')],
        target: 'node',
        format: 'esm',
        minify: false,
        root: join(REPO_ROOT, 'packages/app/src/services'),
        naming: 'history-anatomy.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`history-anatomy bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'history-anatomy.generated.mjs');
    const dmts = join(outDir, 'history-anatomy.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, HISTORY_ANATOMY_DECLS);
    normalizeBundleComments(mjs);
    return { mjs, dmts };
}

/**
 * Bundle the residual-scan pure core (task 1003 R5) into a standalone node-runnable ESM module.
 * Unminified like the digest lib — the source is pure (node:crypto only), so determinism holds.
 * The plugin script `plugins/sp/scripts/residual-scan.ts` keeps the IO glue and imports this.
 */
const RESIDUAL_SCAN_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/services/residual-scan.ts (task 1003 R5).
 */
export declare type ResidualCategory = 'review-finding' | 'diff-marker' | 'unchecked-box' | 'staging-residue';
export declare type ResidualClass = 'blocking' | 'deferrable' | 'advisory' | 'housekeeping';
export declare interface ResidualItem {
    id: string;
    category: ResidualCategory;
    class: ResidualClass;
    priority?: string;
    location: string;
    text: string;
}
export declare interface ResidualArtifact {
    wbs: string;
    base: string | null;
    scanned: Record<ResidualCategory, boolean>;
    items: ResidualItem[];
    counts: { blocking: number; deferrable: number; advisory: number; housekeeping: number };
}
export declare interface Deferral {
    id: string;
    reason: string;
}
export declare interface ResidualScanInputs {
    wbs: string;
    base: string | null;
    taskContent: string;
    addedLines: Array<{ file: string; line: number; text: string }>;
    stagingResidue: string[];
    deferrals: Deferral[];
}
export declare interface FoldResult {
    verdict: 'PASS' | 'PARTIAL' | 'FAIL';
    checks: Array<{ name: string; status: string; evidence: string }>;
    findings: string;
}
export declare interface ParsedScanArgs {
    mode: string;
    wbs: string;
    spurBin?: string;
    root: string;
    tmpDir: string;
}
export declare const ALLOW_PRAGMA: 'residual-scan:allow';
export declare function recordedVerdictPath(runDir: string, wbs: string, fs: Pick<typeof import('node:fs'), 'lstatSync' | 'existsSync'>): string;
export declare function makeItemId(category: ResidualCategory, location: string, text: string): string;
export declare function normalizeAnchor(location: string): string;
export declare function locationOf(locationCell: string, finding: string): string;
export declare function parseReviewFindings(
    taskContent: string,
): Array<{ priority: string; location: string; text: string; deferral?: string }>;
export declare function parseDiffMarkers(
    addedLines: Array<{ file: string; line: number; text: string }>,
): Array<{ location: string; text: string }>;
export declare function findUncheckedBoxes(taskContent: string): Array<{ location: string; text: string }>;
export declare function classify(
    items: Array<Omit<ResidualItem, 'id' | 'class'> & { category: ResidualCategory }>,
    deferrals: Deferral[],
): ResidualItem[];
export declare function scanResiduals(inputs: ResidualScanInputs): ResidualArtifact;
export declare function parseDeferralEntries(raw: unknown): Deferral[];
export declare function blockingReviewFindings(taskContent: string, deferrals: Deferral[]): ResidualItem[];
export declare function buildReviewGateArtifact(
    wbs: string,
    taskContent: string,
    deferrals: Deferral[],
): { artifact: ResidualArtifact; note: string };
export declare function parseScanArgs(
    argv: readonly (string | undefined)[],
    cwd: string,
    defaultTmpDir: string,
): ParsedScanArgs | null;
export declare function blockingAnchors(items: ResidualItem[]): string[];
export declare function foldVerdict(
    verdict: { verdict: string; checks: Array<{ name: string; status: string; evidence: string }> },
    scan: ResidualArtifact,
    existingFindings: string,
    maxFindings?: number,
): FoldResult;
export declare function renderReport(wbs: string, items: ResidualItem[], attemptCount: number): string;
export declare function verdictDisagreementNote(
    runDir: string,
    wbs: string,
    fs: Pick<typeof import('node:fs'), 'existsSync' | 'readFileSync' | 'statSync'>,
): string | null;
`;

export async function bundleResidualScanLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/services/residual-scan.ts')],
        target: 'node',
        format: 'esm',
        minify: false,
        root: join(REPO_ROOT, 'packages/app/src/services'),
        naming: 'residual-scan.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`residual-scan bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'residual-scan.generated.mjs');
    const dmts = join(outDir, 'residual-scan.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, RESIDUAL_SCAN_DECLS);
    normalizeBundleComments(mjs);
    return { mjs, dmts };
}

const QUALITY_GATE_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/services/quality-gate.ts (task 1006 R1).
 */
export declare const MAX_GATE_ATTEMPTS: number;
export declare const MAX_FINDINGS: number;
export declare const RETRY_DELAY_MS_DEFAULT: number;
export declare const RETRY_DELAY_MS_ENV: string;
export declare const LOCKED_PATTERN: RegExp;
export declare const FINDINGS_PATTERN: RegExp;
export declare const COVERAGE_ROW_PATTERN: RegExp;
export declare const RECEIPT_SCHEMA_VERSION: 'check-receipt/v1';
export declare interface QualityGateEnv {
    wbs: string;
    qualityGateCmd?: string;
    gateProbeCmd?: string;
    proofDigest?: string;
    runId?: string;
    [key: string]: string | undefined;
}
export declare interface QualityGateOptions {
    cwd?: string;
}
export declare interface QualityGateResult {
    status: 'PASS' | 'FAIL';
    attempts: number;
    logFile: string;
    findingsFile: string;
    statusFile: string;
    attemptFile: string;
    receiptFile?: string;
}
export declare function isTransientLock(attemptOutput: string): boolean;
export declare function extractFindings(logText: string): string;
export declare function tailLines(text: string, count: number): string;
export declare function retryMessage(attempt: number): string;
export declare interface CoverageThreshold {
    functions?: number;
    lines?: number;
}
export declare function parseCoverageThreshold(bunfigText: string): CoverageThreshold | null;
export declare function scanCoverageShortfalls(logText: string, threshold: CoverageThreshold): string[];
export declare type ReceiptTier = 'full' | 'light';
export declare type CheckStatus = 'PASS' | 'FAIL';
export declare type ReceiptReuseReason = 'missing' | 'failed' | 'stale' | 'light-only';
export declare interface CheckReceiptRow {
    id: string;
    cmd: string;
    status: CheckStatus;
    durationMs: number;
    logPath: string;
}
export declare interface CheckReceipt {
    schemaVersion: 'check-receipt/v1';
    wbs: string;
    runId: string;
    tier: ReceiptTier;
    inputDigest: string;
    checks: CheckReceiptRow[];
    status: CheckStatus;
    completedAt: string;
}
export declare interface ReceiptReadStatus {
    reuse: boolean;
    reason: ReceiptReuseReason | 'ok';
}
export declare interface BuildReceiptInput {
    wbs: string;
    runId: string;
    tier: ReceiptTier;
    inputDigest: string;
    checks: CheckReceiptRow[];
    completedAt: string;
}
export declare function buildReceipt(input: BuildReceiptInput): CheckReceipt;
export declare function receiptFailsAtDigest(receipt: CheckReceipt | null, currentDigest: string): boolean;
export declare function readReceiptStatus(receiptPath: string, currentDigest: string): ReceiptReadStatus;
export declare interface LightScope {
    files: string[];
    workspaces: string[];
    tests: string[];
}
export declare function lightScope(changedFiles: string[], exists?: (p: string) => boolean): LightScope;
export declare function shQuote(arg: string): string;
export declare interface LightCheckPlan {
    id: string;
    cmd: string;
}
export declare function workspaceHasTypecheck(workspace: string): boolean;
export declare function planLightChecks(scope: LightScope, hasTypecheck?: (workspace: string) => boolean): LightCheckPlan[];
export declare interface LightGateResult {
    status: CheckStatus;
    scope: LightScope;
    checks: CheckReceiptRow[];
    logFile: string;
    receiptFile: string;
}
export declare function runLightGate(env: QualityGateEnv, options?: QualityGateOptions): LightGateResult;
export declare interface DeferredGateResult {
    status: 'DEFERRED' | 'FAIL';
    light: LightGateResult;
    statusFile: string;
}
export declare function runDeferredGate(env: QualityGateEnv, options?: QualityGateOptions): DeferredGateResult;
export declare function runShellCommand(cmd: string, cwd: string | undefined): { output: string; code: number };
export declare function runQualityGate(
    mode: 'run' | 'recheck',
    env: QualityGateEnv,
    options?: QualityGateOptions,
): QualityGateResult;
`;

/**
 * Bundle the quality-gate core (task 1006 R1) into a standalone node-runnable ESM module.
 * Unminified — the source is pure (node builtins only: child_process for the merged-fd gate run,
 * fs for gate artifacts), so determinism holds. The plugin script
 * `plugins/sp/scripts/quality-gate.ts` keeps the argv/env glue and re-exports this surface
 * (plugins/sp/tests/quality-gate-receipt.test.ts pins the re-export).
 */
export async function bundleQualityGateLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/services/quality-gate.ts')],
        target: 'node',
        format: 'esm',
        minify: false,
        root: join(REPO_ROOT, 'packages/app/src/services'),
        naming: 'quality-gate.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`quality-gate bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'quality-gate.generated.mjs');
    const dmts = join(outDir, 'quality-gate.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, QUALITY_GATE_DECLS);
    normalizeBundleComments(mjs);
    return { mjs, dmts };
}

const PLAN_PROJECTION_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/workflow/plan-projection.ts (task 1104).
 */
export declare interface PhasedPlanItem {
    label: string;
    id: string;
    outcome: 'pending' | 'active' | 'completed' | 'skipped' | 'failed' | 'blocked' | 'unattempted';
    note?: string;
    text: string;
    parent?: string;
    title?: string;
}
export declare interface BatchTask {
    wbs: string;
    name: string;
}
export declare function planLetter(index: number): string;
export declare function planChild(parent: string, index: number): string;
export declare function buildPhasedPlan(def: unknown): PhasedPlanItem[] | null;
export declare function validatePhaseTable(def: unknown): string[];
export declare function insertOnEntry(items: PhasedPlanItem[], stateId: string, def: unknown): PhasedPlanItem[];
export declare function buildBatchPlan(tasks: BatchTask[]): PhasedPlanItem[][];
export declare function taskPhaseChildren(taskLetter: string, plan: PhasedPlanItem[]): PhasedPlanItem[];
export declare function hostStatus(
    outcome: 'pending' | 'active' | 'completed' | 'skipped' | 'failed' | 'blocked' | 'unattempted',
): 'completed' | 'in_progress' | 'pending';
export declare function hostText(item: PhasedPlanItem): string;
`;

/**
 * Bundle the phased plan projection (task 1104) into a standalone node-runnable ESM module.
 * Unminified and pure (no node builtins) — the module only shapes data; the
 * plugin twin re-exports it so scripts stay thin per ADR-130.
 */
export async function bundlePlanProjectionLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/workflow/plan-projection.ts')],
        target: 'node',
        format: 'esm',
        minify: false,
        root: join(REPO_ROOT, 'packages/app/src/workflow'),
        naming: 'plan-projection.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`plan-projection bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'plan-projection.generated.mjs');
    const dmts = join(outDir, 'plan-projection.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, PLAN_PROJECTION_DECLS);
    normalizeBundleComments(mjs);
    return { mjs, dmts };
}

// ponytail: the .d.mts carries the signatures the workflow handoff consumes; the plugin twin
// only invokes the module, so the env/outcome shapes stay loose on purpose.
const IDEA_HANDOFF_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/workflow/idea-handoff-cli.ts (task 0824).
 */
export declare interface IdeaHandoffCliEnv {
    __runId?: string;
    featureId?: string;
    spurBin?: string;
}
export declare interface IdeaHandoffCliOutcome {
    exitCode: number;
    result?: unknown;
}
export declare function runIdeaHandoffCli(
    env: IdeaHandoffCliEnv,
    run?: (input: { runId: string; featureId: string; spurBin: string }) => Promise<unknown>,
): Promise<IdeaHandoffCliOutcome>;
`;

/**
 * Bundle the idea handoff CLI (task 0824) into a standalone node-runnable ESM module.
 * Minified; `import.meta.main` is pinned to `false` so importing the bundle never triggers
 * the entrypoint block — the plugin twin calls `runIdeaHandoffCli` itself.
 */
export async function bundleIdeaHandoffLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/workflow/idea-handoff-cli.ts')],
        target: 'node',
        format: 'esm',
        minify: { whitespace: true, syntax: true, identifiers: false },
        define: { 'import.meta.main': 'false' },
        root: join(REPO_ROOT, 'packages/app/src/workflow'),
        naming: 'idea-handoff.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`idea handoff bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'idea-handoff.generated.mjs');
    const dmts = join(outDir, 'idea-handoff.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, IDEA_HANDOFF_DECLS);
    return { mjs, dmts };
}

interface InlineRunExport {
    name: string;
    /** Repo-relative source module, no extension. */
    from: string;
    /** The full `.d.mts` line for `name`. */
    declare: string;
}

const appExports = (from: string, ...names: string[]): InlineRunExport[] =>
    names.map((name) => ({
        name,
        from,
        declare: `export declare const ${name}: typeof import('@gobing-ai/spur-app').${name};`,
    }));

/**
 * The inline-run surface: one row per export (task 0972). The bundle entry and the `.d.mts` are
 * both derived from it, so a name cannot be exported without being declared (or vice versa).
 * Row order is the entry's module/name order — changing it changes the generated `.mjs`.
 */
const INLINE_RUN_EXPORTS: readonly InlineRunExport[] = [
    // Task 0975 verify P1: the worktree close-out path (--persist-out) and the
    // --decide mode are driver-facade calls (`app.persistWorktreeRuns` /
    // `app.runDecideForInlineRun`); omitting them left both dead in installed
    // layouts. plugins/sp/tests/inline-run-installed.test.ts pins facade↔twin parity.
    ...appExports(
        'packages/app/src/services/inline-run-setup',
        'appendInlineRunLogLine',
        'createOrAttachInlineRun',
        'inlineRunRecordLogPath',
        'isInlineRunActionStatus',
        'isInlineRunCloseStatus',
        'openInlineRunProjectDb',
        'persistWorktreeRuns',
        // Task 1070: the installed-CLI inventory walk moved into the app service (ADR-130 glue
        // budget) — the facade calls it, so both twins must export it.
        'readInstalledInventory',
        'runDecideForInlineRun',
        // Task 1006 R3: mode runners moved into the app service; the plugin script dispatches them.
        // Task 1007 R5: the driver's per-state batch emission (`--actions-file`).
        'runInlineRunTraceBatch',
        'runInlineRunDecide',
        'runInlineRunFingerprint',
        'runInlineRunPersistOut',
        'runInlineRunSetup',
        'runInlineRunTrace',
        'writeInlineRunOutcome',
    ),
    ...appExports(
        'packages/app/src/workflow/proof-input-fingerprint',
        'computeProofInputFingerprint',
        'readProofInputContents',
    ),
    ...appExports('packages/app/src/workflow/action-trace', 'createWorkflowActionTraceWriter'),
    {
        name: 'splitLaunchCommand',
        from: 'packages/app/src/workflow/split-launch-command',
        declare:
            'export declare function splitLaunchCommand(value: string, label: string): { command: string; leadingArgs: string[] } | { error: string };',
    },
    // Feature verification receipt (D63 task 0915): the standard script
    // records/validates receipts and resolves the selected verifier
    // definition through the same seams in both layouts.
    ...appExports(
        'packages/app/src/workflow/feature-verification-receipt',
        'captureFeatureReceiptDigest',
        'completeFeatureVerificationReceipt',
        'DEFAULT_FEATURE_VERIFICATION_CMD',
        'featureReceiptPaths',
        'startFeatureVerificationReceipt',
        'validateFeatureVerificationReceipt',
    ),
    ...appExports('packages/app/src/workflow/workflow-resolver', 'resolveWorkflowDefinition'),
    // Decide-enabled switch (task 0941 gate fix): the facade derivation the delegate
    // calls at its composition boundary — the app service takes the flag as an
    // explicit parameter (ADR-082), so the loader call stays out of app services.
    {
        name: 'resolveDecideDecisionMakerEnabled',
        from: 'packages/config/src/loader',
        declare:
            "export declare const resolveDecideDecisionMakerEnabled: typeof import('@gobing-ai/spur-config/loader').resolveDecideDecisionMakerEnabled;",
    },
    // Catalog-reference decide (task 1094): the delegate loads the merged config once at the
    // driver boundary and threads it into runInlineRunDecide (ADR-082).
    {
        name: 'loadSpurConfig',
        from: 'packages/config/src/loader',
        declare: "export declare const loadSpurConfig: typeof import('@gobing-ai/spur-config/loader').loadSpurConfig;",
    },
    ...['ArtifactDao', 'RunDao'].map((name) => ({
        name,
        from: 'packages/domain/src/dao',
        declare: `export declare const ${name}: typeof import('@gobing-ai/spur-domain').${name};`,
    })),
    {
        name: 'EMBEDDED_SPUR_SCHEMAS',
        from: 'apps/cli/src/config/embedded-schemas',
        declare: 'export declare const EMBEDDED_SPUR_SCHEMAS: ReadonlyMap<string, string>;',
    },
];

/** One `export { … } from` line per source module, in first-seen row order. */
function inlineRunEntry(): string {
    const byModule = new Map<string, string[]>();
    for (const { name, from } of INLINE_RUN_EXPORTS) {
        byModule.set(from, [...(byModule.get(from) ?? []), name]);
    }
    return [...byModule].map(([from, names]) => `export { ${names.join(', ')} } from '../${from}';`).join('\n');
}

/** Bundle only the inline driver's existing application operations and schema assets. */
export async function bundleInlineRunLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    // Keep the temporary entry inside the repo so workspace dependencies resolve consistently.
    // ponytail: fixed scratch path — the mkdtemp suffix leaked into Bun's minified
    // identifier assignment and broke the determinism gate; builds are serialized.
    const scratch = join(REPO_ROOT, '.inline-run-bundle');
    try {
        mkdirSync(scratch, { recursive: true });
        const entry = join(scratch, 'entry.ts');
        writeFileSync(entry, inlineRunEntry());
        const result = await Bun.build({
            entrypoints: [entry],
            target: 'node',
            format: 'esm',
            minify: { whitespace: true, syntax: true, identifiers: false },
            external: ['bun:sqlite'],
            define: { 'import.meta.main': 'false' },
            naming: 'inline-run.generated.mjs',
            outdir: outDir,
        });
        if (!result.success) {
            throw new Error(`inline run bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
        }
        const mjs = join(outDir, 'inline-run.generated.mjs');
        const dmts = join(outDir, 'inline-run.generated.d.mts');
        writeFileSync(
            dmts,
            [
                '/** GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit. Requires Bun for SQLite. */',
                ...INLINE_RUN_EXPORTS.map((e) => e.declare),
                '',
            ].join('\n'),
        );
        return { mjs, dmts };
    } finally {
        rmSync(scratch, { recursive: true, force: true });
    }
}

if (import.meta.main) {
    const stepProfile = await bundleStepProfileLib();
    console.log(`step-profile lib generated: ${stepProfile.mjs}, ${stepProfile.dmts}`);
    const historyAnatomy = await bundleHistoryAnatomyLib();
    console.log(`history-anatomy lib generated: ${historyAnatomy.mjs}, ${historyAnatomy.dmts}`);
    const handoff = await bundleIdeaHandoffLib();
    console.log(`idea-handoff lib generated: ${handoff.mjs}, ${handoff.dmts}`);
    const inlineRun = await bundleInlineRunLib();
    console.log(`inline-run lib generated: ${inlineRun.mjs}, ${inlineRun.dmts}`);
    const residual = await bundleResidualScanLib();
    console.log(`residual-scan lib generated: ${residual.mjs}, ${residual.dmts}`);
    const qualityGate = await bundleQualityGateLib();
    console.log(`quality-gate lib generated: ${qualityGate.mjs}, ${qualityGate.dmts}`);
    const planProjection = await bundlePlanProjectionLib();
    console.log(`plan-projection lib generated: ${planProjection.mjs}, ${planProjection.dmts}`);
}
