/**
 * Generate the plugin-side copy of the domain artifact-digest authority (task 0669).
 *
 * `packages/domain/src/analytics/artifact-digest.ts` owns the semantic digest, but the plugin
 * script `plugins/sp/scripts/history-anatomy-cache.ts` is an ADR-065 standard script: its committed
 * `.mjs` twin must run under bare `node` with no monorepo dependency, and `superskill script
 * convert` cannot bundle a `@gobing-ai/spur-domain` import. The bridge is a **generated** ESM
 * bundle under `plugins/sp/lib/`, committed, imported by the script through a relative path —
 * which the twin generator inlines successfully (proven in task 0669 Q&A probes).
 *
 * Outputs (both gitignored from Biome, both committed):
 *   plugins/sp/lib/artifact-digest.generated.mjs    — standalone ESM bundle of the authority
 *   plugins/sp/lib/artifact-digest.generated.d.mts  — declarations for the surface the script uses
 *
 * `bundleIdeaHandoffLib` (task 0824) applies the same bridge to the idea-pipeline handoff
 * writer: `packages/app/src/workflow/idea-handoff-cli.ts` is bundled (minified, with
 * `import.meta.main` pinned to false) into `plugins/sp/lib/idea-handoff.generated.mjs` so the
 * registered standard twin `plugins/sp/scripts/idea-handoff.mjs` runs under bare `node` in
 * seeded projects with no monorepo checkout.
 *
 * Run via `bun run build:plugin-lib`; chained ahead of `build:scripts`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const REPO_ROOT = new URL('../../', import.meta.url).pathname;
const ENTRY = join(REPO_ROOT, 'packages/domain/src/analytics/artifact-digest.ts');
const OUT_DIR = join(REPO_ROOT, 'plugins/sp/lib');

// ponytail: the .d.mts carries the fixed signatures the script consumes; widen here (not by hand
// in the lib file) if the script ever imports more of the authority.
const DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/domain/src/analytics/artifact-digest.ts (task 0669).
 */
export declare const ARTIFACT_ARRAY_CLASSIFICATION: Readonly<Record<string, 'ranked' | 'set'>>;
export declare const RANKED_ARTIFACT_KEYS: ReadonlySet<string>;
export declare function semanticArtifactDigest(artifactJson: unknown): string;
`;

export async function bundlePluginLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [ENTRY],
        target: 'node',
        format: 'esm',
        minify: false,
        root: join(REPO_ROOT, 'packages/domain/src/analytics'),
        naming: 'artifact-digest.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`plugin-lib bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'artifact-digest.generated.mjs');
    const dmts = join(outDir, 'artifact-digest.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, DECLS);
    return { mjs, dmts };
}

// ponytail: the .d.mts carries the signatures the workflow handoff consumes; the plugin twin
// only invokes the module, so the env/outcome shapes stay loose on purpose.
const IDEA_HANDOFF_DECLS = `/**
 * GENERATED by scripts/commands/bundle-plugin-lib.ts — do not edit.
 * Source of truth: packages/app/src/workflow/idea-handoff-cli.ts (task 0824).
 */
export declare interface IdeaHandoffCliEnv {
    __runId?: string;
    featureId?: string;
    spurBin?: string;
}
export declare interface IdeaHandoffCliOutcome {
    exitCode: number;
    result?: unknown;
}
export declare function runIdeaHandoffCli(
    env: IdeaHandoffCliEnv,
    run?: (input: { runId: string; featureId: string; spurBin: string }) => Promise<unknown>,
): Promise<IdeaHandoffCliOutcome>;
`;

/**
 * Bundle the idea handoff CLI (task 0824) into a standalone node-runnable ESM module.
 * Minified; `import.meta.main` is pinned to `false` so importing the bundle never triggers
 * the entrypoint block — the plugin twin calls `runIdeaHandoffCli` itself.
 */
export async function bundleIdeaHandoffLib(outDir: string = OUT_DIR): Promise<{ mjs: string; dmts: string }> {
    const result = await Bun.build({
        entrypoints: [join(REPO_ROOT, 'packages/app/src/workflow/idea-handoff-cli.ts')],
        target: 'node',
        format: 'esm',
        minify: true,
        define: { 'import.meta.main': 'false' },
        root: join(REPO_ROOT, 'packages/app/src/workflow'),
        naming: 'idea-handoff.generated.mjs',
        outdir: outDir,
    });
    if (!result.success) {
        throw new Error(`idea handoff bundle failed: ${result.logs.map((l) => String(l)).join('\n')}`);
    }
    const mjs = join(outDir, 'idea-handoff.generated.mjs');
    const dmts = join(outDir, 'idea-handoff.generated.d.mts');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(dmts, IDEA_HANDOFF_DECLS);
    return { mjs, dmts };
}

if (import.meta.main) {
    const { mjs, dmts } = await bundlePluginLib();
    console.log(`plugin-lib generated: ${mjs}, ${dmts}`);
    const handoff = await bundleIdeaHandoffLib();
    console.log(`idea-handoff lib generated: ${handoff.mjs}, ${handoff.dmts}`);
}
