/**
 * Emit the declaration-only `@gobing-ai/spur/board` artifact (task 0988 R1).
 *
 * `apps/web/src/modules/contribution.ts` is the single authoring source: the CLI package
 * must not import React, must not re-declare the ABI by hand, and must not ship a runtime
 * module for `./board`. This command runs the TypeScript compiler in
 * `emitDeclarationOnly` mode over that one source file and writes the resulting `.d.ts`
 * to `apps/cli/board/index.d.ts`, which `apps/cli/package.json` exposes as `./board`.
 *
 * Repo-internal dev-script, NOT a new public `spur` noun/verb (ADR-051).
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));

/** The single authoring source for the public contribution ABI. */
export const BOARD_AUTHORING_SOURCE = join(REPO_ROOT, 'apps/web/src/modules/contribution.ts');

/** Declared shape the generated artifact must contain (frozen output, task 0988). */
export const BOARD_DECLARATION_REQUIRED_LINES: readonly string[] = [
    'export interface BoardModuleContribution {',
    'readonly apiVersion: 1;',
    'readonly component: ComponentType;',
    'readonly rightPanelComponent?: ComponentType;',
    'export declare const webModule: BoardModuleContribution;',
];

const HEADER =
    '// Generated by scripts/commands/emit-board-types.ts from\n' +
    '// apps/web/src/modules/contribution.ts — edit the authoring source, then regenerate.\n';

/** Path of the generated artifact inside the published CLI package. */
export function boardDeclarationTarget(repoRoot: string = REPO_ROOT): string {
    return join(repoRoot, 'apps/cli/board/index.d.ts');
}

/**
 * Declaration text for the authoring source — deterministic and compiler-derived.
 * Fails loudly if the compiler did not produce exactly one declaration file.
 */
export function renderBoardDeclaration(): string {
    const options: ts.CompilerOptions = {
        declaration: true,
        emitDeclarationOnly: true,
        target: ts.ScriptTarget.ESNext,
        module: ts.ModuleKind.ESNext,
        moduleResolution: ts.ModuleResolutionKind.Bundler,
        strict: true,
        skipLibCheck: true,
        types: [],
    };
    const program = ts.createProgram({ rootNames: [BOARD_AUTHORING_SOURCE], options });
    const source = program.getSourceFile(BOARD_AUTHORING_SOURCE);
    if (!source) throw new Error(`emit-board-types: cannot load ${BOARD_AUTHORING_SOURCE}`);

    const emitted = new Map<string, string>();
    const diagnostics = program.getSemanticDiagnostics(source);
    if (diagnostics.length > 0) {
        throw new Error(
            `emit-board-types: ${BOARD_AUTHORING_SOURCE} does not compile:\n${ts.formatDiagnosticsWithColorAndContext(diagnostics, hostFor(source))}`,
        );
    }
    program.emit(source, (fileName, text) => void emitted.set(fileName, text), undefined, true);

    if (emitted.size !== 1) {
        throw new Error(`emit-board-types: expected exactly one declaration file, got ${emitted.size}`);
    }
    const declaration = [...emitted.values()][0] as string;
    const body = `${HEADER}${declaration.trimEnd()}\n`;

    for (const line of BOARD_DECLARATION_REQUIRED_LINES) {
        if (!body.includes(line)) {
            throw new Error(
                `emit-board-types: the frozen contribution ABI line "${line}" is missing from the generated artifact`,
            );
        }
    }
    if (/^\s*import\s+(?!type\b)/m.test(body) || body.includes('require(')) {
        throw new Error('emit-board-types: the artifact must not contain a React value import');
    }
    return body;
}

/** Formatting host for compiler diagnostics (no project tsconfig is loaded here). */
function hostFor(source: ts.SourceFile): ts.FormatDiagnosticsHost {
    return {
        getCanonicalFileName: (f) => f,
        getCurrentDirectory: () => dirname(source.fileName),
        getNewLine: () => '\n',
    };
}

/** Write the artifact. Returns the target path plus whether the file changed on disk. */
export async function emitBoardDeclarations(
    target: string = boardDeclarationTarget(),
): Promise<{ target: string; changed: boolean }> {
    const text = renderBoardDeclaration();
    const existing = await readFile(target, 'utf-8').catch(() => undefined);
    if (existing === text) return { target, changed: false };
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, text, 'utf-8');
    return { target, changed: true };
}
