/**
 * Guard: the published `@gobing-ai/spur/board` declaration is GENERATED from the authoring source
 * (`apps/web/src/modules/contribution.ts`) and cannot drift from it.
 *
 * Task 0988 R1: one authoring source, a declaration-only artifact, no React value import anywhere in
 * the CLI surface.
 */
import { describe, expect, test } from 'bun:test';
import { readFile } from 'node:fs/promises';
import {
    BOARD_AUTHORING_SOURCE,
    BOARD_DECLARATION_REQUIRED_LINES,
    boardDeclarationTarget,
    renderBoardDeclaration,
} from './emit-board-types';

describe('emit-board-types', () => {
    test('the committed artifact is exactly what the authoring source generates', async () => {
        const onDisk = await readFile(boardDeclarationTarget(), 'utf-8');
        expect(onDisk).toBe(renderBoardDeclaration());
    });

    test('the artifact states the frozen ABI and the entry export name', () => {
        const declaration = renderBoardDeclaration();
        for (const line of BOARD_DECLARATION_REQUIRED_LINES) expect(declaration).toContain(line);
        expect(declaration).toContain('export declare const webModule: BoardModuleContribution;');
        expect(declaration.split('\n')[0]).toBe('// Generated by scripts/commands/emit-board-types.ts from');
        expect(declaration).toContain('apps/web/src/modules/contribution.ts');
        expect(BOARD_AUTHORING_SOURCE.endsWith('apps/web/src/modules/contribution.ts')).toBeTrue();
    });

    test('the artifact is declaration-only: no runtime React import, no require', () => {
        const declaration = renderBoardDeclaration();
        expect(declaration).toContain("import type { ComponentType } from 'react';");
        expect(/^\s*import\s+(?!type\b)/m.test(declaration)).toBeFalse();
        expect(declaration).not.toContain('require(');
        // No implementation body leaks in: only declarations are emitted.
        expect(/\bfunction\s+\w+\s*\(/.test(declaration)).toBeFalse();
    });

    test('regeneration is deterministic', () => {
        expect(renderBoardDeclaration()).toBe(renderBoardDeclaration());
    });
});
