import type { HistoryArtifact } from './artifact';
import { renderForensics } from './render-forensics';
import { renderReport } from './render-report';

/**
 * A report mode renderer: pure `HistoryArtifact → string`, no I/O, no `DbAdapter`. Built-in
 * TS functions only — no template engine, no variable-binding contract, no config surface
 * (operator ruling 2026-08-09).
 */
export type ReportRenderer = (artifact: HistoryArtifact) => string;

/** Thrown when `--mode` names no registered renderer; the message names the registered set. */
export class UnknownReportModeError extends Error {
    constructor(mode: string, registered: readonly string[]) {
        super(`Unknown report mode '${mode}'. Registered modes: ${registered.join(', ')}`);
        this.name = 'UnknownReportModeError';
    }
}

/**
 * The report mode registry (0555 R1). It **subsumes** the former `renderReport` /
 * `renderMarkdown` call path — callers resolve a renderer here rather than importing a
 * renderer directly, so there is exactly one rendering entry point for the next mode to
 * extend. `default` preserves today's output byte-for-byte.
 */
export const REPORT_MODES: Readonly<Record<string, ReportRenderer>> = {
    default: renderReport,
    forensics: renderForensics,
};

/** Resolve `--mode <name>` to its renderer; unknown names fail naming the registered set. */
export function resolveReportMode(mode: string): ReportRenderer {
    const renderer = REPORT_MODES[mode];
    if (renderer === undefined) {
        throw new UnknownReportModeError(mode, Object.keys(REPORT_MODES));
    }
    return renderer;
}

/**
 * Render the markdown sidecar body (R8 of the original report task, mode-aware since 0555):
 * the selected mode's output wrapped in a fenced block with a one-line header. Lives beside
 * the registry — not in `render-report.ts` — so the registry stays the only rendering path
 * and no import cycle arises.
 */
export function renderMarkdown(artifact: HistoryArtifact, mode = 'default'): string {
    const header = `<!-- Generated by spur history report · schema v${artifact.schemaVersion} · ${artifact.generatedAt} -->`;
    const body = resolveReportMode(mode)(artifact);
    return `${header}\n\n\`\`\`\n${body}\n\`\`\`\n`;
}
